/**
 * The Deep's dive quest layer: data plus pure helpers. The data lives in
 * ./dives-data.js, generated by `node tools/gen_dive_quests.mjs` from
 * WebXR/smartcity/js/curricula.js and the seabed's own sites and landmarks
 * (read through ./seabed.js). This file never edits that data; it combines
 * it and offers pure functions over it, the way bayworld/js/quests.js does.
 *
 * Dives name sites and landmarks by their display names (`dive.site`,
 * `egg.landmark`); the seabed keys them by id. dvResolveDiveSite() and
 * dvResolveLandmark() bridge the two so the game (dives-select.js) and the
 * checker (tools/check_dive_quests.mjs) agree.
 */
import { DV_MAIN_DIVES, DV_SIDE_DIVES, DV_EGG_DIVES, DV_ACTIVITIES, DV_LANDMARK_NOTES } from "./dives-data.js";

export { DV_MAIN_DIVES, DV_SIDE_DIVES, DV_EGG_DIVES, DV_ACTIVITIES, DV_LANDMARK_NOTES };

/** Every dive dvRegisterDives() should receive: main arc, side dives, eggs. */
export const DV_ALL_DIVES = [...DV_MAIN_DIVES, ...DV_SIDE_DIVES, ...DV_EGG_DIVES];

export function dvGetDiveById(id, dives = DV_ALL_DIVES) { return dives.find((q) => q.id === id) ?? null; }
export function dvDivesByKind(kind, dives = DV_ALL_DIVES) { return dives.filter((q) => q.kind === kind); }
export function dvDivesForProgramme(programmeId, dives = DV_SIDE_DIVES) { return dives.filter((q) => q.programmeId === programmeId); }

/** Every distinct station id a dive's "station" steps name, in order. */
export function dvStationIdsInDive(dive) {
  const ids = [];
  for (const step of dive.steps) if (step.type === "station" && !ids.includes(step.target)) ids.push(step.target);
  return ids;
}

/** Every distinct landmark name an egg dive is sited at. */
export function dvLandmarksCited(dives = DV_ALL_DIVES) {
  return [...new Set(dvDivesByKind("egg", dives).map((q) => q.landmark).filter(Boolean))];
}

// --------------------------------------------------------------- rewards

const DV_XP_BASE = 100;
const DV_XP_STEP = 150;
/** The same monotone curve tools/gen_dive_quests.mjs used: base 100, +150 per tier. */
export function dvRewardForTier(tier) {
  if (!Number.isInteger(tier) || tier < 1) throw new Error(`dvRewardForTier: tier must be a positive integer, got ${tier}`);
  return DV_XP_BASE + (tier - 1) * DV_XP_STEP;
}

/** Every main/side dive whose reward.xp is not dvRewardForTier(tier). */
export function dvRewardMonotonicityViolations(dives = DV_ALL_DIVES) {
  const out = [];
  for (const q of dives) {
    if (q.kind === "egg") continue;
    const expected = dvRewardForTier(q.tier);
    if (q.reward?.xp !== expected) out.push({ id: q.id, tier: q.tier, expectedXp: expected, actualXp: q.reward?.xp });
  }
  return out;
}

// ------------------------------------------------------------ dive graph

/** The first `requires` cycle, as ids, or null when the graph is a DAG. */
export function dvFindCycle(dives = DV_ALL_DIVES) {
  const byId = new Map(dives.map((q) => [q.id, q]));
  const color = new Map(dives.map((q) => [q.id, 0]));
  const stack = [];
  function visit(id) {
    color.set(id, 1); stack.push(id);
    const next = byId.get(id)?.requires;
    if (next && byId.has(next)) {
      if (color.get(next) === 1) return [...stack.slice(stack.indexOf(next)), next];
      if (color.get(next) === 0) { const found = visit(next); if (found) return found; }
    }
    stack.pop(); color.set(id, 2);
    return null;
  }
  for (const q of dives) if (color.get(q.id) === 0) { const found = visit(q.id); if (found) return found; }
  return null;
}

// ------------------------------------------------------------ resolution

/** The seabed site a dive happens at: by programme anchor for side dives,
 *  else by exact id or name. */
export function dvResolveDiveSite(dive, sites) {
  if (!Array.isArray(sites)) return null;
  if (dive.programmeId) { const s = sites.find((x) => (x.programmes || []).includes(dive.programmeId)); if (s) return s; }
  return sites.find((x) => x.id === dive.site || x.name === dive.site) || null;
}

/** The seabed landmark a lantern hides at: by exact id or name. */
export function dvResolveLandmark(name, landmarks) {
  if (!Array.isArray(landmarks)) return null;
  return landmarks.find((x) => x.id === name || x.name === name) || null;
}
