/**
 * The catalog roster the console browses: categories → programmes → stations,
 * folded out of WebXR/smartcity/catalog.json (generated by
 * tools/gen_catalog.mjs) and nothing else. The console never imports simulator
 * code — this is the same static roster a hosting platform can index without
 * loading an app at all, which is exactly what an instructor needs to send a
 * class somewhere.
 *
 * Kept in its own module, with no DOM in it, so tools/check_console.mjs can
 * assert the tree covers every station in the catalog rather than trusting a
 * screenshot of the page.
 */

/** One flat row per station, in catalog order, with its category attached. */
export function stationRows(catalog) {
  const stations = Array.isArray(catalog?.stations) ? catalog.stations : [];
  return stations.map((s) => ({
    app: s.app ?? "smartcity",
    id: s.id,
    name: s.name ?? s.id,
    category: s.category ?? "Uncategorized",
    trade: s.trade ?? "",
    certification: s.certification ?? "",
    tagline: s.tagline ?? "",
    steps: s.steps ?? 0,
    interrupts: s.interrupts ?? 0,
    weather: s.weather ?? "clear",
    parSeconds: s.parSeconds ?? 0,
    flat: !!s.flat,
  }));
}

/**
 * The tree the Roster view renders. Categories come from the stations
 * themselves (so a station in a since-renamed category is still reachable),
 * in the order `catalog.categories` lists them, with anything the category
 * list does not mention appended rather than dropped.
 */
export function buildRoster(catalog) {
  const rows = stationRows(catalog);
  const order = (Array.isArray(catalog?.categories) ? catalog.categories : []).map((c) => c.name);
  const byCategory = new Map();
  for (const name of order) byCategory.set(name, []);
  for (const row of rows) {
    if (!byCategory.has(row.category)) byCategory.set(row.category, []);
    byCategory.get(row.category).push(row);
  }
  const categories = [...byCategory.entries()]
    .filter(([, list]) => list.length > 0)
    .map(([name, list]) => ({ name, stations: list }));
  const programmes = (Array.isArray(catalog?.curricula) ? catalog.curricula : []).map((c) => ({
    id: c.id,
    name: c.name ?? c.id,
    union: c.union ?? "",
    certification: c.certification ?? "",
    summary: c.summary ?? "",
    stations: (c.stations ?? []).map((s) => ({ app: s.app ?? "smartcity", id: s.id, why: s.why ?? "" })),
  }));
  return {
    categories,
    programmes,
    stations: rows,
    total: rows.length,
    weatherKinds: Array.isArray(catalog?.weather?.kinds) ? catalog.weather.kinds : [],
  };
}

/** Case-insensitive match over the fields an instructor would actually type:
 *  the station's id, name, category, trade and certification. */
export function matchStation(row, query) {
  const q = String(query ?? "").trim().toLowerCase();
  if (!q) return true;
  return [row.id, row.name, row.category, row.trade, row.certification, row.tagline]
    .some((v) => String(v ?? "").toLowerCase().includes(q));
}

/** A programme matches on its own words or on any station it contains. */
export function matchProgramme(programme, query) {
  const q = String(query ?? "").trim().toLowerCase();
  if (!q) return true;
  if ([programme.id, programme.name, programme.union, programme.certification, programme.summary]
    .some((v) => String(v ?? "").toLowerCase().includes(q))) return true;
  return programme.stations.some((s) => s.id.toLowerCase().includes(q));
}
