// SmartCiti.X TradeQuest adapter (console TQ-BRIDGE, docs/tradequest-bridge.md).
//
// Turns the Holodeck shared export (exports/shared/holodeck-shared.json, contract
// `smartcitix-holodeck-shared`, v2) into the registry shapes the Trade Craft Academy site
// reads: registries are `{ pack, provenance, status, note, items }` objects, as the site's own
// registries and street-fabric files are (`{ pack, provenance: "AUTHORED", note, … }`), with the
// site's provenance vocabulary (AUTHORED, SCHEMATIC, PROCEDURAL, GENERATED, PENDING).
//
// Dependency-free ESM: no imports, no DOM, no network, no clock. Pure — the same document
// always gives the same output. A v1 document is accepted too: its places come from
// `parishes` and every v2-only registry reads `pending`.
//
//     import { tqAdapt } from "./tradequest-adapter.js";
//     const tq = tqAdapt(JSON.parse(text));
//     tq.registries.places.items[0].sites[0].stations;   // station ids at a site
//     tq.stationIndex["dock-crane"];                      // where a station plays
//     tq.pending;                                         // registries still waiting on an owner

export const TQ_ADAPTER_VERSION = "1.0.0";
export const TQ_CONTRACT = "smartcitix-holodeck-shared";
export const TQ_REGISTRIES = ["places", "courses", "paths", "finishes", "kit", "fleet", "scenarios", "dataset"];

/** The Holodeck region → the TradeQuest campus a place is offered under (AUTHORED routing, not geography; null = no campus yet). */
export const TQ_CAMPUS_BY_REGION = {
  "new-orleans": "new-orleans",
  "san-francisco": "treasure-island",
  oakland: "oakland",
  "north-east-bay": "oakland",
  "south-bay": null,
  "bay-program": null,
};

/** The provenance words the site uses, and what each means here. */
export const TQ_PROVENANCE = {
  AUTHORED: "written for the platform by a person or a console; names real places only as places",
  SCHEMATIC: "the shape or look of a thing, not a measurement of one",
  PROCEDURAL: "generated by a seeded procedure at run time",
  GENERATED: "generated from SmartCiti.X curricula (the catalogue and programmes)",
  PENDING: "the owner has not published this section yet; re-run tools/export_shared.mjs after it merges",
};

const arr = (v) => (Array.isArray(v) ? v : []);
const major = (v) => Number(String(v ?? "0").split(".")[0]) || 0;

/** Can this adapter read `doc`? `{ ok, major, why }`. */
export function tqAccepts(doc) {
  if (!doc || typeof doc !== "object") return { ok: false, major: 0, why: "not an object" };
  if (doc.contract !== TQ_CONTRACT) return { ok: false, major: 0, why: `contract is not ${TQ_CONTRACT}` };
  const m = major(doc.version);
  if (m < 1 || m > 2) return { ok: false, major: m, why: `version ${doc.version} is outside 1.x–2.x` };
  return { ok: true, major: m, why: "" };
}

/** A registry: the site's shape. `status` is ready | partial | pending. */
const registry = (pack, provenance, status, items, extra = {}) => ({
  pack, provenance: status === "pending" ? "PENDING" : provenance, status, ...extra, items,
});

const sec = (doc, key) => (doc?.[key] && typeof doc[key] === "object" && "status" in doc[key] ? doc[key] : { status: "pending", data: null });

function places(doc) {
  const frames = new Map(arr(doc.parishes).map((p) => [p.id, p]));
  const maps = sec(doc, "maps");
  const src = maps.status !== "pending" && maps.data ? arr(maps.data.maps) : arr(doc.parishes).map((p) => ({ id: p.id, name: p.name, region: p.region, sites: arr(p.sites).map((s) => ({ id: s.id, name: s.id, kind: null, stations: arr(s.stations) })), landmarks: [], hills: [] }));
  const items = src.map((m) => {
    const f = frames.get(m.id);
    return {
      id: m.id, name: m.name, region: m.region, campus: TQ_CAMPUS_BY_REGION[m.region] ?? null,
      frame: f ? { centre: f.centre, bounds: f.bounds, fips: f.fips ?? null } : null,
      sites: arr(m.sites).map((s) => ({ id: s.id, name: s.name, kind: s.kind ?? null, stations: arr(s.stations).slice() })),
      landmarks: arr(m.landmarks).map((l) => ({ id: l.id, name: l.name, lm: l.lm ?? null })),
      hills: arr(m.hills).map((h) => ({ id: h.id, name: h.name })),
    };
  });
  const regions = maps.data?.regions ? arr(maps.data.regions).map((r) => ({ id: r.id, name: r.name, campus: TQ_CAMPUS_BY_REGION[r.id] ?? null, places: arr(r.maps).slice() })) : [];
  return registry("places", "AUTHORED", items.length ? (maps.status === "pending" ? "partial" : "ready") : "pending", items, {
    regions, note: "Real places are named only as places; layouts are stylised and frames are approximate fits, not survey data.",
  });
}

function courses(doc) {
  const items = arr(doc.packs).map((p) => ({ id: p.id, title: p.title, programmes: arr(p.programmes).slice(), stations: arr(p.stations).slice(), path: p.path ?? null }));
  return registry("courses", "GENERATED", items.length ? "ready" : "pending", items, { source: doc.packsSource ?? null });
}

function paths(doc) {
  const items = arr(doc.paths).map((id) => ({ id, courses: arr(doc.packs).filter((p) => p.path === id).map((p) => p.id) }));
  return registry("paths", "AUTHORED", items.length ? "ready" : "pending", items);
}

function finishes(doc) {
  const s = sec(doc, "palette");
  const c = s.data?.categories;
  const items = Array.isArray(c) ? c : c && typeof c === "object" ? Object.entries(c).map(([id, v]) => ({ id, ...(typeof v === "object" && !Array.isArray(v) ? v : { colours: v }) })) : [];
  return registry("finishes", "SCHEMATIC", s.status === "pending" ? "pending" : s.status, items, { note: "Colour categories by district character and region (PALETTE's PA_CATEGORIES)." });
}

function kit(doc) {
  const s = sec(doc, "facades");
  const k = s.data?.detailKinds;
  const families = Array.isArray(k) ? k : k && typeof k === "object" ? Object.entries(k).map(([id, v]) => ({ id, ...(typeof v === "object" && !Array.isArray(v) ? v : { detail: v }) })) : [];
  return registry("kit", "SCHEMATIC", s.status, families, { signs: arr(s.data?.signs).slice(), note: "Facade detail families and the generic sign list (FACADES); sign text is generic trades only, never a real business name." });
}

function fleet(doc) {
  const s = sec(doc, "vehicles");
  const items = arr(s.data?.drivables).map((d) => ({ id: d.id, name: d.name, medium: d.medium, class: d.class, trades: arr(d.trades).slice(), gatedOn: arr(d.gate?.stations).slice(), handling: d.profile ?? null }));
  const mv = s.data?.motorworks;
  return registry("fleet", "AUTHORED", s.status, items, { classes: arr(s.data?.classes).slice(), motorworks: mv && mv.status !== "pending" ? mv : null, note: "Every vehicle is gated on its pre-trip station(s); handling figures are game units, not specifications." });
}

function scenarios(doc) {
  const s = sec(doc, "robotics");
  return registry("scenarios", "PROCEDURAL", s.status, arr(s.data?.scenarios).slice(), { api: s.data?.api ?? null, note: "Robots never harm people in any scenario; scoring is on safe practice." });
}

function dataset(doc) {
  const s = sec(doc, "dataset");
  const d = s.data ?? {};
  return registry("dataset", "AUTHORED", s.status, [], {
    episodes: d.episodes ?? null, embodiment: d.embodiment ?? null, episodeSchema: d.episodeSchema ?? null, datasetCard: d.datasetCard ?? null,
    note: "Schemas and templates only — no episode and no learner data travel in this export.",
  });
}

/** Where each station plays: `{ stationId: [{ place, site, campus }] }`. */
export function tqStationIndex(placesRegistry) {
  const out = {};
  for (const p of arr(placesRegistry?.items)) for (const s of arr(p.sites)) for (const id of arr(s.stations)) (out[id] ??= []).push({ place: p.id, site: s.id, campus: p.campus });
  return out;
}

/** The whole mapping. Throws only when `tqAccepts(doc)` says no. */
export function tqAdapt(doc) {
  const acc = tqAccepts(doc);
  if (!acc.ok) throw new Error(`tradequest-adapter: ${acc.why}`);
  const registries = { places: places(doc), courses: courses(doc), paths: paths(doc), finishes: finishes(doc), kit: kit(doc), fleet: fleet(doc), scenarios: scenarios(doc), dataset: dataset(doc) };
  return {
    pack: "holodeck-shared",
    packVersion: doc.version,
    adapter: TQ_ADAPTER_VERSION,
    contract: TQ_CONTRACT,
    provenance: TQ_PROVENANCE,
    pending: TQ_REGISTRIES.filter((k) => registries[k].status === "pending"),
    registries,
    stationIndex: tqStationIndex(registries.places),
  };
}
