// SmartCiti.X TradeQuest adapter (console TQ-BRIDGE, docs/tradequest-bridge.md).
//
// Turns the Holodeck shared export (exports/shared/holodeck-shared.json, contract
// `smartcitix-holodeck-shared`, v2) into the registry shapes the Trade Craft Academy site
// reads: registries are `{ pack, provenance, status, note, items }` objects, as the site's own
// registries and street-fabric files are (`{ pack, provenance: "AUTHORED", note, … }`), with the
// site's provenance vocabulary (AUTHORED, SCHEMATIC, PROCEDURAL, GENERATED, PENDING).
//
// Dependency-free ESM: no imports, no DOM, no network, no clock. Pure — the same document
// always gives the same output. A v1 document is accepted too: its places come from
// `parishes` and every v2-only registry reads `pending`.
//
//     import { tqAdapt } from "./tradequest-adapter.js";
//     const tq = tqAdapt(JSON.parse(text));
//     tq.registries.places.items[0].sites[0].stations;   // station ids at a site
//     tq.stationIndex["dock-crane"];                      // where a station plays
//     tq.pending;                                         // registries still waiting on an owner
//
// 1.1.0 (console TQ-ROBOTICS) adds three registries read from the robotics `programme` facet:
//     tq.registries.pathways.items[0].levels[1].stations[0].launch;   // "smartcity-x.html?sim=<station>&from=tradequest"
//     tq.registries.credentials.items[0].earnedAt;                    // [{ pathway, level }]
//     tq.registries.launch.items;                                     // station and site links, relative to the Holodeck's deployed root
// and the `scenarios` registry carries the AGENTGYM and COLEARN summaries and, when VBRIDGE has published them, the
// safety governor's rules and the job phases. A 2.0 or v1 document still adapts: the new registries read `pending`.

export const TQ_ADAPTER_VERSION = "1.1.0";
export const TQ_CONTRACT = "smartcitix-holodeck-shared";
export const TQ_REGISTRIES = ["places", "courses", "paths", "finishes", "kit", "fleet", "scenarios", "dataset", "pathways", "credentials", "launch"];

/** The Holodeck region → the TradeQuest campus a place is offered under (AUTHORED routing, not geography; null = no campus yet). */
export const TQ_CAMPUS_BY_REGION = {
  "new-orleans": "new-orleans",
  "san-francisco": "treasure-island",
  oakland: "oakland",
  "north-east-bay": "oakland",
  "south-bay": null,
  "bay-program": null,
};

/** The provenance words the site uses, and what each means here. */
export const TQ_PROVENANCE = {
  AUTHORED: "written for the platform by a person or a console; names real places only as places",
  SCHEMATIC: "the shape or look of a thing, not a measurement of one",
  PROCEDURAL: "generated by a seeded procedure at run time",
  GENERATED: "generated from SmartCiti.X curricula (the catalogue and programmes)",
  PENDING: "the owner has not published this section yet; re-run tools/export_shared.mjs after it merges",
};

const arr = (v) => (Array.isArray(v) ? v : []);
const major = (v) => Number(String(v ?? "0").split(".")[0]) || 0;

/** Can this adapter read `doc`? `{ ok, major, why }`. */
export function tqAccepts(doc) {
  if (!doc || typeof doc !== "object") return { ok: false, major: 0, why: "not an object" };
  if (doc.contract !== TQ_CONTRACT) return { ok: false, major: 0, why: `contract is not ${TQ_CONTRACT}` };
  const m = major(doc.version);
  if (m < 1 || m > 2) return { ok: false, major: m, why: `version ${doc.version} is outside 1.x–2.x` };
  return { ok: true, major: m, why: "" };
}

/** A registry: the site's shape. `status` is ready | partial | pending. */
const registry = (pack, provenance, status, items, extra = {}) => ({
  pack, provenance: status === "pending" ? "PENDING" : provenance, status, ...extra, items,
});

const sec = (doc, key) => (doc?.[key] && typeof doc[key] === "object" && "status" in doc[key] ? doc[key] : { status: "pending", data: null });

function places(doc) {
  const frames = new Map(arr(doc.parishes).map((p) => [p.id, p]));
  const maps = sec(doc, "maps");
  const src = maps.status !== "pending" && maps.data ? arr(maps.data.maps) : arr(doc.parishes).map((p) => ({ id: p.id, name: p.name, region: p.region, sites: arr(p.sites).map((s) => ({ id: s.id, name: s.id, kind: null, stations: arr(s.stations) })), landmarks: [], hills: [] }));
  const items = src.map((m) => {
    const f = frames.get(m.id);
    return {
      id: m.id, name: m.name, region: m.region, campus: TQ_CAMPUS_BY_REGION[m.region] ?? null,
      frame: f ? { centre: f.centre, bounds: f.bounds, fips: f.fips ?? null } : null,
      sites: arr(m.sites).map((s) => ({ id: s.id, name: s.name, kind: s.kind ?? null, stations: arr(s.stations).slice() })),
      landmarks: arr(m.landmarks).map((l) => ({ id: l.id, name: l.name, lm: l.lm ?? null })),
      hills: arr(m.hills).map((h) => ({ id: h.id, name: h.name })),
    };
  });
  const regions = maps.data?.regions ? arr(maps.data.regions).map((r) => ({ id: r.id, name: r.name, campus: TQ_CAMPUS_BY_REGION[r.id] ?? null, places: arr(r.maps).slice() })) : [];
  return registry("places", "AUTHORED", items.length ? (maps.status === "pending" ? "partial" : "ready") : "pending", items, {
    regions, note: "Real places are named only as places; layouts are stylised and frames are approximate fits, not survey data.",
  });
}

function courses(doc) {
  const items = arr(doc.packs).map((p) => ({ id: p.id, title: p.title, programmes: arr(p.programmes).slice(), stations: arr(p.stations).slice(), path: p.path ?? null }));
  return registry("courses", "GENERATED", items.length ? "ready" : "pending", items, { source: doc.packsSource ?? null });
}

function paths(doc) {
  const items = arr(doc.paths).map((id) => ({ id, courses: arr(doc.packs).filter((p) => p.path === id).map((p) => p.id) }));
  return registry("paths", "AUTHORED", items.length ? "ready" : "pending", items);
}

function finishes(doc) {
  const s = sec(doc, "palette");
  const c = s.data?.categories;
  const items = Array.isArray(c) ? c : c && typeof c === "object" ? Object.entries(c).map(([id, v]) => ({ id, ...(typeof v === "object" && !Array.isArray(v) ? v : { colours: v }) })) : [];
  return registry("finishes", "SCHEMATIC", s.status === "pending" ? "pending" : s.status, items, { note: "Colour categories by district character and region (PALETTE's PA_CATEGORIES)." });
}

function kit(doc) {
  const s = sec(doc, "facades");
  const k = s.data?.detailKinds;
  const families = Array.isArray(k) ? k : k && typeof k === "object" ? Object.entries(k).map(([id, v]) => ({ id, ...(typeof v === "object" && !Array.isArray(v) ? v : { detail: v }) })) : [];
  return registry("kit", "SCHEMATIC", s.status, families, { signs: arr(s.data?.signs).slice(), note: "Facade detail families and the generic sign list (FACADES); sign text is generic trades only, never a real business name." });
}

function fleet(doc) {
  const s = sec(doc, "vehicles");
  const items = arr(s.data?.drivables).map((d) => ({ id: d.id, name: d.name, medium: d.medium, class: d.class, trades: arr(d.trades).slice(), gatedOn: arr(d.gate?.stations).slice(), handling: d.profile ?? null }));
  const mv = s.data?.motorworks;
  return registry("fleet", "AUTHORED", s.status, items, { classes: arr(s.data?.classes).slice(), motorworks: mv && mv.status !== "pending" ? mv : null, note: "Every vehicle is gated on its pre-trip station(s); handling figures are game units, not specifications." });
}

function scenarios(doc) {
  const s = sec(doc, "robotics");
  const d = s.status === "pending" ? null : s.data;
  const f = (k) => (d?.facets?.[k]?.status === "ready" ? d[k] : null);
  return registry("scenarios", "PROCEDURAL", s.status, arr(d?.scenarios).slice(), {
    api: d?.api ?? null, rules: d?.rules ?? null, ssm: d?.ssm ?? null,
    // The facets of the robotics section (2.1.0): null while pending; `facets` says which and why.
    facets: d?.facets ?? null, agentGym: f("agentGym"), colearn: f("colearn"), governor: f("governor"), jobs: f("jobs"),
    note: "Robots never harm people in any scenario; scoring is on safe practice. A command from a software agent reaches a simulated robot only, through the safety governor.",
  });
}

/** Where the Holodeck's pages take a TradeQuest learner. Paths are relative to the Holodeck's deployed root; TradeQuest adds its own base. No host is named here. */
export const TQ_LAUNCH = { station: "smartcity-x.html?sim=", place: "parishes.html?parish=", from: "tradequest" };
const q = encodeURIComponent;
export const tqStationLaunch = (id) => `${TQ_LAUNCH.station}${q(id)}&from=${TQ_LAUNCH.from}`;
export const tqPlaceLaunch = (place, site = null) => `${TQ_LAUNCH.place}${q(place)}${site ? `&site=${q(site)}` : ""}&from=${TQ_LAUNCH.from}`;

const roboticsFacet = (doc, k) => {
  const s = sec(doc, "robotics");
  return s.status !== "pending" && s.data?.facets?.[k]?.status === "ready" ? s.data[k] : null;
};
const has = (o, k) => Object.prototype.hasOwnProperty.call(o ?? {}, k);

/** The robotics pathway catalogue: six tracks, five levels each, with stations (and launch links), standards by name and the credential each level ends in. */
function pathways(doc) {
  const P = roboticsFacet(doc, "programme");
  const std = new Map(arr(P?.standards).map((x) => [x.id, x.label]));
  const lv = new Map(arr(P?.levels).map((x) => [x.id, x]));
  const robot = P?.robotStations ?? {};
  const items = arr(P?.tracks).map((t) => ({
    id: t.id, title: t.title, kinds: t.kinds, scenario: t.scenario,
    standards: arr(t.standards).map((id) => ({ id, label: std.get(id) ?? id })),
    sites: arr(t.rbSites).slice(),
    levels: arr(t.ladder).map((r) => ({
      id: r.level, title: lv.get(r.level)?.title ?? r.level, requiredScore: lv.get(r.level)?.requiredScore ?? null, dueDays: lv.get(r.level)?.dueDays ?? null,
      stations: arr(r.stations).map((id) => ({ id, robot: has(robot, id), launch: tqStationLaunch(id) })),
      capstone: arr(r.capstone).slice(), credential: r.credential ?? null, earnable: !!r.earnable, collectsData: r.level === "ai-training",
    })),
  }));
  return registry("pathways", "AUTHORED", P ? "ready" : "pending", items, {
    levels: arr(P?.levels).map((x) => ({ id: x.id, title: x.title })), standards: arr(P?.standards).map((x) => ({ id: x.id, label: x.label })),
    loop: arr(P?.loop).slice(), coverage: P?.coverage ?? null, consent: P?.consent ?? null, note: P?.note ?? null,
  });
}

/** The credentials the pathways end in (ids on the SmartCiti.X competency layer; TradeQuest maps them to its own names). */
function credentials(doc) {
  const P = roboticsFacet(doc, "programme");
  const items = Object.entries(P?.credentials ?? {}).map(([id, c]) => ({
    id, title: c.title, require: c.require,
    earnedAt: arr(P?.tracks).flatMap((t) => arr(t.ladder).filter((r) => r.credential === id).map((r) => ({ pathway: t.id, level: r.level }))),
  })).sort((a, b) => (a.id < b.id ? -1 : 1));
  return registry("credentials", "AUTHORED", P ? "ready" : "pending", items, { note: "Competency ids; a credential is earned by passing its stations at the level's required score. No payment, token or ranking is attached." });
}

/** Station and site launch links for the robotics pathways, with where each station plays. */
function launch(doc, placesRegistry) {
  const P = roboticsFacet(doc, "programme");
  const idx = tqStationIndex(placesRegistry);
  const where = new Map();
  for (const t of arr(P?.tracks)) for (const r of arr(t.ladder)) for (const id of [...arr(r.stations), ...arr(r.capstone)]) {
    if (!where.has(id)) where.set(id, []);
    where.get(id).push({ pathway: t.id, level: r.level });
  }
  for (const id of Object.keys(P?.robotStations ?? {})) if (!where.has(id)) where.set(id, []);
  const stations = [...where.keys()].sort().map((id) => ({
    id, kind: "station", launch: tqStationLaunch(id), robot: has(P?.robotStations, id), robotKind: P?.robotStations?.[id] ?? null,
    pathways: where.get(id), places: (idx[id] ?? []).map((p) => ({ ...p })),
  }));
  const rb = sec(doc, "robotics");
  const sites = P ? arr(rb.data?.sites).map((s) => ({ id: s.id, kind: "site", name: s.name, rig: s.rig ?? null, place: s.parish, scenario: s.scenario ?? null, station: s.station ?? null, launch: tqPlaceLaunch(s.parish, s.anchor) })) : [];
  return registry("launch", "AUTHORED", P ? "ready" : "pending", [...stations, ...sites], {
    base: { ...TQ_LAUNCH }, note: "Paths are relative to the Holodeck's deployed root; the site adds its own base. A site opens its map at the building the robot rig stands beside. Every robot in a station or site is simulated.",
  });
}

function dataset(doc) {
  const s = sec(doc, "dataset");
  const d = s.data ?? {};
  return registry("dataset", "AUTHORED", s.status, [], {
    episodes: d.episodes ?? null, embodiment: d.embodiment ?? null, episodeSchema: d.episodeSchema ?? null, datasetCard: d.datasetCard ?? null,
    note: "Schemas and templates only — no episode and no learner data travel in this export.",
  });
}

/** Where each station plays: `{ stationId: [{ place, site, campus }] }`. */
export function tqStationIndex(placesRegistry) {
  const out = {};
  for (const p of arr(placesRegistry?.items)) for (const s of arr(p.sites)) for (const id of arr(s.stations)) (out[id] ??= []).push({ place: p.id, site: s.id, campus: p.campus });
  return out;
}

/** The whole mapping. Throws only when `tqAccepts(doc)` says no. */
export function tqAdapt(doc) {
  const acc = tqAccepts(doc);
  if (!acc.ok) throw new Error(`tradequest-adapter: ${acc.why}`);
  const placesRegistry = places(doc);
  const registries = { places: placesRegistry, courses: courses(doc), paths: paths(doc), finishes: finishes(doc), kit: kit(doc), fleet: fleet(doc), scenarios: scenarios(doc), dataset: dataset(doc), pathways: pathways(doc), credentials: credentials(doc), launch: launch(doc, placesRegistry) };
  return {
    pack: "holodeck-shared",
    packVersion: doc.version,
    adapter: TQ_ADAPTER_VERSION,
    contract: TQ_CONTRACT,
    provenance: TQ_PROVENANCE,
    pending: TQ_REGISTRIES.filter((k) => registries[k].status === "pending"),
    registries,
    stationIndex: tqStationIndex(registries.places),
  };
}
