// COGNITION — the in-world learning module runner (docs/consoles/COGNITION.md, "Seams").
//
// Seams (exported, documented shapes):
//   cgUnits() -> CG_UNITS (unit -> lessons -> flow, generated by tools/gen_cg_units.mjs)
//   cgLessonsAt({ world, parish?, site? }) -> lessons taught there (any of a lesson's places: parish lesson sites, field lesson anchors, Redwood sites), each with `here`
//   cgFlowRunner(flow, { lesson, character, report, at }) -> { say(), next(ev), phase, state, run, done }
//     a pure state machine over a flowhub flow (flowhub.js startRun/advance/evaluateGate): greet -> each node ->
//     done. say() returns { who, line, options?, note?, href?, actions } in by-flow-agent.js's shape, so
//     byMountFlowAgent (BAYOU) renders it unchanged. next(ev): {} to move on, { passed } after a station,
//     { answer } at a check (a miss takes the flow's own fallback edge: the simpler re-teach step, then back),
//     { done } after an apply step.
//   cgReport(lesson, run, report, { misses }) -> the lesson report { lesson, station, unit, flow, status, steps, reteaches, misses, at, where }, handed (guarded) to SCHOLAR's scStartSession(lessonId, where)
//     shape and DEAN's module progress shape: report.scholar?.(lessonId, where) and report.dean?.({ module, lesson, status, at }).
//   cgGuideFor(lesson, fallbackId) -> { id, name, role } | null — the GRIOT character (npc-data.js) who speaks the lesson.
//   cgMountRunner(el, { world, parish?, site?, character?, guide?, report? }) -> { open(lessonId), lessons, current } (plain DOM, no three.js).
//   cgWorldReport(toast?) -> the report hooks a world passes: SCHOLAR (globalThis.scStartSession) and DEAN (globalThis.dnModuleProgress), guarded.
// Reduced motion: nothing here animates.

import { startRun, advance, position, evaluateGate, acknowledgedOutcome } from "./flowhub.js";
import { byMountFlowAgent } from "./by-flow-agent.js";
import { CG_UNITS, CG_FLOWS } from "./cg-units.js";
import { GR_ROSTER } from "./npc-data.js";

export const CG_PHASES = ["greet", "brief", "lesson", "check", "apply", "close", "done"];

export function cgUnits() { return CG_UNITS; }
export function cgFlow(id) { return CG_FLOWS[id] ?? null; }
export function cgLessonsAt({ world, parish = null, site = null } = {}) {
  const out = [];
  for (const u of CG_UNITS) for (const l of u.lessons) {
    const w = [l.where, ...(l.places ?? [])].find((p) => p && p.world === world
      && !(parish && p.parish && p.parish !== parish) && !(site && p.site && p.site !== site));
    if (!w || out.some((o) => o.station === l.station)) continue;
    out.push({ ...l, unit: u.id, here: w });
  }
  return out;
}

/** The GRIOT character who guides a lesson: the parish lesson's own guide, else the fallback id the world passes. */
export function cgGuideFor(lesson, fallbackId = null) {
  // the guide of the place the lesson plays at (a parish lesson's own guide never follows it to another map)
  const id = (lesson?.here ? lesson.here.guide : lesson?.where?.guide) ?? fallbackId;
  const g = id ? GR_ROSTER.find((c) => c.id === id) : null;
  return g ? { id: g.id, name: g.name, role: g.role } : null;
}

const cgLinkFor = (node) => (node?.ref ? `../smartcity/index.html?sim=${encodeURIComponent(node.ref)}&from=cognition` : null);

/** The display phase byMountFlowAgent keys its buttons on. */
function cgPhaseOf(node, isLast) {
  if (!node) return "done";
  if (node.kind === "station" || node.kind === "programme") return "lesson";
  if (node.kind === "checkin" && node.params?.check) return "check";
  if (node.kind === "external") return "apply";
  if (node.kind === "checkin" && isLast) return "close";
  return "brief";
}

export function cgFlowRunner(flow, { lesson = null, character = null, report = null, at = () => Date.now() } = {}) {
  const who = character?.name ? `${character.name}, ${String(character.role ?? character.title ?? "guide").toLowerCase()}` : "your guide";
  const state = { greeted: false, tries: 0, lastWhy: null, reteaches: 0, log: [], reported: null };
  let run = startRun(flow, { at: at(), source: "cognition" });
  const node = () => (run.done ? null : position(run, flow));
  const isLast = (n) => !!n && !(flow.edges ?? []).some((e) => e.from === n.id);
  const phase = () => (!state.greeted ? "greet" : run.done ? "done" : cgPhaseOf(node(), isLast(node())));

  function say() {
    const n = node();
    const ph = phase();
    if (ph === "greet") return { who, line: `Welcome. Today's lesson: ${lesson?.title ?? flow.title}.`, actions: ["start"] };
    if (ph === "done") return { who, line: "Lesson complete.", actions: [] };
    if (ph === "lesson") return { who, line: `Open the station and work it through: ${n.title}.`, href: cgLinkFor(n), actions: ["passed", "try again"] };
    if (ph === "check") { const c = n.params.check; return { who, line: c.q, options: c.options, note: state.lastWhy, actions: ["answer"] }; }
    if (ph === "apply") return { who, line: `Now use it here: ${n.title}.`, actions: ["done"] };
    if (ph === "close") return { who, line: "How did that go? Say one thing you would tell someone at home.", actions: ["finish"] };
    // a brief speaks the lesson's own lines (parish or field lesson steps), a re-teach its simpler step titles
    const lines = n.params?.reteach ?? (n.kind === "brief" && lesson?.steps?.length ? lesson.steps : n.kind === "brief" ? [n.why] : [n.title]);
    return { who, line: lines.join(" "), note: n.params?.reteach ? "One step at a time." : null, actions: ["next"] };
  }

  function step(outcome) { run = advance(run, flow, outcome, { at: at() }).run; }

  function next(ev = {}) {
    const from = phase();
    const n = node();
    if (from === "greet") state.greeted = true;
    else if (from === "lesson") step({ passed: !!ev.passed, stars: ev.passed ? 2 : 0, hazardHits: 0, ref: n.ref });
    else if (from === "check") {
      state.tries++;
      const right = ev.answer === n.params.check.answer;
      state.lastWhy = right ? null : (n.params.check.why ?? null);
      // A flow that branches on the check (COGNITION's) takes its re-teach edge on a miss; one that does not
      // (BAYOU's) keeps the learner on the check with its why, as by-flow-agent.js does.
      const branches = (flow.edges ?? []).some((e) => e.from === n.id && e.when?.passed === true);
      if (!right) state.reteaches++;
      if (right || branches) step({ ...acknowledgedOutcome(), passed: right });
    } else if (from === "apply") { if (ev.done) step(acknowledgedOutcome()); }
    else if (n?.kind === "gate") step(evaluateGate(n, run, flow));
    else if (from !== "done") step(acknowledgedOutcome());
    state.log.push([from, phase()]);
    if (run.done && !state.reported) state.reported = cgReport(lesson, run, report, { misses: state.reteaches });
    return say();
  }

  return { say, next, state, flow, lesson, get phase() { return phase(); }, get run() { return run; }, get done() { return run.done; } };
}

/** The lesson report: SCHOLAR's session and DEAN's module progress, both guarded (either may be absent). */
export function cgReport(lesson, run, report = null, extra = {}) {
  const rec = {
    lesson: lesson?.id ?? null, station: lesson?.station ?? null, unit: lesson?.unit ?? null, flow: run?.flowId ?? null,
    status: run?.done ? "complete" : "in-progress", steps: (run?.history ?? []).length,
    reteaches: (run?.history ?? []).filter((h) => h.next === "reteach").length, misses: extra.misses ?? null, at: run?.updatedAt ?? null,
    where: lesson?.where ?? null,
  };
  try { report?.scholar?.(rec.lesson, rec.where); } catch { /* SCHOLAR absent or refused: the lesson still completes */ }
  try { report?.dean?.({ module: rec.unit, lesson: rec.lesson, status: rec.status, at: rec.at }); } catch { /* DEAN absent */ }
  try { report?.onReport?.(rec); } catch { /* caller hook */ }
  return rec;
}

const cgEsc = (s) => String(s ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]);

/** Plain-DOM mount: a lesson list for this place; a lesson plays through byMountFlowAgent. */
export function cgMountRunner(el, { world, parish = null, site = null, character = null, guide = null, report = null } = {}) {
  if (!el) return null;
  const lessons = cgLessonsAt({ world, parish, site });
  el.textContent = "";
  if (!lessons.length) return { open: () => null, lessons };
  const head = document.createElement("p");
  head.className = "eyebrow"; head.style.marginTop = "16px";
  head.textContent = `Learning module · ${lessons.length} K-12 lesson${lessons.length === 1 ? "" : "s"} here`;
  const row = document.createElement("div");
  row.className = "row"; row.style.flexWrap = "wrap";
  const panel = document.createElement("div");
  panel.className = "cg-runner";
  let current = null;
  function open(id) {
    const l = lessons.find((x) => x.id === id || x.station === id);
    const flow = l && cgFlow(l.flow);
    if (!flow) return null;
    current = cgFlowRunner(flow, { lesson: l, character: character ?? cgGuideFor(l, guide), report });
    panel.textContent = "";
    const box = document.createElement("div");
    panel.appendChild(box);
    byMountFlowAgent(box, current);
    return current;
  }
  for (const l of lessons.slice(0, 8)) {
    const b = document.createElement("button");
    b.type = "button"; b.className = "btn"; b.dataset.cgLesson = l.id;
    b.innerHTML = cgEsc(l.title);
    b.addEventListener("click", () => open(l.id));
    row.appendChild(b);
  }
  el.append(head, row, panel);
  return { open, lessons, get current() { return current; } };
}

/** The report hooks a world mounts with: SCHOLAR's and DEAN's shapes when their modules are loaded, guarded either way. */
export function cgWorldReport(toast = null) {
  return {
    scholar: (lessonId, where) => globalThis.scStartSession?.(lessonId, where),
    dean: (p) => globalThis.dnModuleProgress?.(p),
    onReport: (rec) => toast?.(`Lesson complete: ${rec.station ?? rec.lesson}${rec.reteaches ? " (with a re-teach step)" : ""}`),
  };
}
