// Ladders — twenty levels per programme, and who has climbed them.
//
// A level (smartcity/js/ladders.js, generated by tools/gen_ladders.mjs) is an
// ordered chain of tasks run back to back with one shared score, one results
// card and one badge (tools/briefs/ladder-brief.md). A task is a station run
// under one CONDITION — the base run, an hour of the day, a weather, hazard
// mode pinned to assessed, an instructor-style interruption, or an assessment
// variant (CONDITIONS below) — and a level's LESSONS are its tasks' steps
// added up. This module is the rule layer over that data and the record:
//
//   - levelState(ladder, records): locked / open / passed for every level.
//     A level PASSES when one run of it has a mastery run (competency.js's
//     MASTERY, nothing else) on every one of its tasks. Level 1 is always
//     open; level N opens when level N-1 has passed. No other path unlocks a
//     level — not an instructor, not a score, not a streak.
//   - a level run: startLevelRun / nextTask / recordTask / levelResult, the
//     plain object the app keeps while a chain is being played. It survives a
//     trip to Trade Skills and back in one localStorage key, the way a flow
//     does (shared/flowhub.js), because some programmes chain a Trade Skills
//     room into a level.
//   - levelBadge / levelXAPI: the Open Badges 2.0 assertion a passed level
//     earns and the xAPI statement a finished level sends.
//
// Pure: no DOM, no three.js, no import of an app. The only import is the
// mastery rule itself, so the rule that gates a level is the rule that earns
// a competency. tools/check_ladders.mjs runs all of it in Node.

import { MASTERY, masteryShortfall } from "./competency.js";

export const LADDER_LEVELS = 20;
/** The lessons a level must hold (the sum of its tasks' steps); fewer is `partial`. */
export const LESSON_BAR = 75;
/** The one localStorage key a level run lives under while it is being played. */
export const LEVEL_RUN_KEY = "vr-training-ladder-run-v1";
export const LEVEL_STATES = ["locked", "open", "passed"];

// ------------------------------------------------------------------ conditions
//
// A condition is one string. Every one of them maps onto a query parameter the
// SmartCiti.X app reads, so a task launched from a level, a deep link on a
// track page and an instructor's hand-typed URL all run the same thing:
//
//   base                    the station as authored            (no parameter)
//   time:day | time:dusk    the hour, via stage.js             ?time=
//   weather:<kind>          a weather.js kind                  ?weather=
//   hazard                  hazard mode pinned to assessed     ?hazard=assess
//   interrupt:<id>          one declared interruption, fired   ?interrupt=<id>
//                           off its authored step
//   variant:assessment      shared/variants.js makeVariant     ?variant=&seed=
//   variant:pressure
//
// Night is the stage's default hour, so it is the base run and not a
// condition of its own; stage.js has no dawn and weather.js has no heat, so
// neither is offered. Trade Skills reads none of these parameters: a task in
// that app is always `base`.

export const CONDITION_TIMES = ["day", "dusk"];
/** weather.js's WEATHER_KINDS less "clear" (the default); tools/check_ladders.mjs holds the two in step. */
export const CONDITION_WEATHER = ["overcast", "rain", "fog", "wind", "storm", "smoke"];
export const CONDITION_VARIANTS = ["assessment", "pressure"];
/** The query keys a condition may set; a level task clears all of them before setting its own. */
export const CONDITION_KEYS = ["time", "weather", "hazard", "interrupt", "variant", "seed"];

/** "kind:value" → { kind, value }, or null when it is not a condition this ladder knows. */
export function parseCondition(cond) {
  const s = String(cond ?? "");
  if (s === "base" || s === "hazard") return { kind: s, value: null };
  const m = /^(time|weather|interrupt|variant):([a-z0-9][a-z0-9-]{0,63})$/.exec(s);
  if (!m) return null;
  const [, kind, value] = m;
  if (kind === "time" && !CONDITION_TIMES.includes(value)) return null;
  if (kind === "weather" && !CONDITION_WEATHER.includes(value)) return null;
  if (kind === "variant" && !CONDITION_VARIANTS.includes(value)) return null;
  return { kind, value };
}

/**
 * Whether a station can honestly run under a condition. `station` carries
 * { app, indoor, hazards, interrupts: [{ id }] } — the numbers the ladder's
 * station table holds. Weather is refused indoors (an interior hides the
 * weather, so the run would not differ), hazard mode on a station with no
 * registered hazard, an interruption the station does not declare, and
 * everything but `base` in Trade Skills.
 */
export function conditionValid(cond, station) {
  const c = parseCondition(cond);
  if (!c || !station) return false;
  if (c.kind === "base") return true;
  if (station.app === "trades") return false;
  if (c.kind === "weather") return !station.indoor;
  if (c.kind === "hazard") return (station.hazards | 0) > 0;
  if (c.kind === "interrupt") return (station.interrupts ?? []).some((i) => i.id === c.value);
  return true;
}

/** The query parameters a condition sets, as [key, value] pairs. `seed` makes a variant reproducible. */
export function conditionParams(cond, { seed = null } = {}) {
  const c = parseCondition(cond);
  if (!c || c.kind === "base") return [];
  if (c.kind === "time") return [["time", c.value]];
  if (c.kind === "weather") return [["weather", c.value]];
  if (c.kind === "hazard") return [["hazard", "assess"]];
  if (c.kind === "interrupt") return [["interrupt", c.value]];
  return [["variant", c.value], ...(seed != null ? [["seed", String(seed)]] : [])];
}

/** The condition a URL's query asks for — the inverse of conditionParams — or "base". */
export function conditionFromQuery(search) {
  const q = new URLSearchParams(search ?? "");
  const pick = [
    q.get("variant") && `variant:${q.get("variant")}`,
    q.get("interrupt") && `interrupt:${q.get("interrupt")}`,
    q.get("hazard") === "assess" && "hazard",
    q.get("weather") && `weather:${q.get("weather")}`,
    q.get("time") && `time:${q.get("time")}`,
  ].find((c) => c && parseCondition(c));
  return pick || "base";
}

/** A short label for a chip. */
export function conditionLabel(cond) {
  const c = parseCondition(cond);
  if (!c) return String(cond ?? "");
  if (c.kind === "base") return "base run";
  if (c.kind === "hazard") return "hazard mode";
  if (c.kind === "time") return c.value === "day" ? "daylight" : "dusk";
  if (c.kind === "weather") return c.value === "wind" ? "high wind" : c.value === "smoke" ? "wildfire smoke" : c.value;
  if (c.kind === "interrupt") return `interruption: ${c.value.replace(/-/g, " ")}`;
  return c.value === "assessment" ? "assessment variant" : "under pressure";
}

/** The pair a task is: "app:id@condition". No level names one twice, and no two adjacent levels share one. */
export function taskKey(t) {
  return `${t.app}:${t.id}@${t.condition ?? "base"}`;
}

/** "programme:level" (an instructor's CMD_ASSIGN detail, a deep link) → parts, or null. */
export function parseLevelRef(ref) {
  const m = /^([a-z0-9][a-z0-9-]{0,63}):(\d{1,2})$/.exec(String(ref ?? "").trim());
  if (!m) return null;
  const level = Number(m[2]);
  return level >= 1 && level <= LADDER_LEVELS ? { programme: m[1], level } : null;
}

/** One level of a ladder by number. */
export function ladderLevel(ladder, n) {
  return (ladder?.levels ?? []).find((l) => l.n === n) ?? null;
}

/** The ladder tag an attempt carries when it was played as part of a level run. */
export function levelTag(run, index = null) {
  if (!run) return null;
  return { programme: run.programme, level: run.level, run: run.id, task: index ?? (run.attempts?.length ?? 0) };
}

/**
 * The runs of one level that the record holds, each with its attempts per
 * task, and the first run (by its earliest attempt) in which every task has a
 * mastery run. Attempts without a ladder tag never count: a level is passed
 * by playing the level, not by having once played its stations separately.
 */
function levelRuns(programme, level, records) {
  const runs = new Map();
  for (const r of records ?? []) {
    const t = r?.ladder;
    if (!t || t.programme !== programme || t.level !== level.n || !t.run) continue;
    if (!runs.has(t.run)) runs.set(t.run, []);
    runs.get(t.run).push(r);
  }
  let passed = null;
  for (const [id, list] of runs) {
    // A task is a station under a condition, and a level may name the same
    // station twice under two conditions: an attempt counts for the task at
    // its own place in the chain, played under that task's condition.
    const mastered = level.tasks.every((task, i) => list.some((r) => r.simId === task.id
      && (r.ladder.task == null || r.ladder.task === i)
      && (r.condition ?? "base") === (task.condition ?? "base")
      && masteryShortfall(r) === null));
    if (!mastered) continue;
    const at = list.map((r) => String(r.at ?? "")).sort().pop();
    if (!passed || at < passed.at) passed = { run: id, at };
  }
  return { attempts: runs.size, passed };
}

/**
 * Where a learner stands on every level of one ladder. Returns twenty rows in
 * order: { n, title, state, passedAt, run, runs, steps, lessons, tasks, partial }.
 */
export function levelState(ladder, records = []) {
  const out = [];
  let prevPassed = true; // level 1 is always open
  for (let n = 1; n <= LADDER_LEVELS; n++) {
    const level = ladderLevel(ladder, n);
    if (!level) { out.push({ n, state: "locked", missing: true }); prevPassed = false; continue; }
    const { attempts, passed } = levelRuns(ladder.programme, level, records);
    const state = !prevPassed ? "locked" : passed ? "passed" : "open";
    out.push({
      n, title: level.title, state,
      passedAt: state === "passed" ? passed.at : null,
      run: state === "passed" ? passed.run : null,
      runs: attempts,
      steps: level.steps, lessons: level.lessons ?? level.steps, tasks: level.tasks.length,
      conditions: level.tasks.map((t) => t.condition ?? "base"),
      partial: !!level.partial, shortfall: level.shortfall | 0,
      coaching: level.coaching !== false,
    });
    prevPassed = state === "passed";
  }
  return out;
}

// ------------------------------------------------------------------ level runs

/** A fresh run of level `n`: the tasks in order, nothing played yet. */
export function startLevelRun(ladder, n, { at = new Date().toISOString(), id = null } = {}) {
  const level = ladderLevel(ladder, n);
  if (!level) return null;
  return {
    v: 1,
    id: id ?? `lvl-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 7)}`,
    programme: ladder.programme,
    level: n,
    title: level.title,
    coaching: level.coaching !== false,
    tasks: level.tasks.map((t) => ({ app: t.app, id: t.id, condition: t.condition ?? "base", steps: t.steps })),
    interruptions: (level.interruptions ?? []).map((i) => ({ task: i.task, id: i.id })),
    attempts: [],
    startedAt: at,
    done: false,
  };
}

/** The task the run stands on — { app, id, condition, steps, index, of } — or null when every task is played. */
export function nextTask(levelRun) {
  if (!levelRun || levelRun.done) return null;
  const i = levelRun.attempts?.length ?? 0;
  const t = levelRun.tasks?.[i];
  return t ? { ...t, index: i, of: levelRun.tasks.length } : null;
}

/** What a level run keeps of one attempt: the fields the mastery rule and the results card read. */
function compactAttempt(a) {
  const iv = a.interrupts ?? a.debrief?.interrupts ?? null;
  const shortfall = masteryShortfall(a);
  return {
    attemptId: a.id ?? null, at: a.at ?? null, app: a.app ?? null, simId: a.simId, simName: a.simName ?? a.simId,
    condition: a.condition ?? "base",
    score: a.score | 0, stars: a.stars | 0, errors: a.errors | 0, hazardHits: a.hazardHits | 0,
    seconds: a.seconds | 0, parSeconds: a.parSeconds ?? null,
    interrupts: iv ? { answered: iv.answered | 0, wrong: iv.wrong | 0, missed: iv.missed | 0 } : null,
    mastery: shortfall === null, reason: shortfall?.reason ?? null,
  };
}

/**
 * The run with one more task played. An attempt on anything but the task the
 * run stands on — another station, or the same station under another
 * condition — is ignored (the run is returned unchanged), so a station
 * played on the side can never be folded into a level.
 */
export function recordTask(levelRun, attempt) {
  const t = nextTask(levelRun);
  if (!t || !attempt || attempt.simId !== t.id) return levelRun;
  if ((attempt.condition ?? "base") !== (t.condition ?? "base")) return levelRun;
  const attempts = [...levelRun.attempts, compactAttempt(attempt)];
  return { ...levelRun, attempts, done: attempts.length >= levelRun.tasks.length };
}

/**
 * The level's verdict from a run: the shared score (the sum of the tasks'
 * scores), total time against total par, one row per task, and `passed` —
 * true only when every task was played and every one is a mastery run.
 */
export function levelResult(levelRun) {
  const rows = (levelRun?.tasks ?? []).map((t, i) => {
    const a = levelRun.attempts?.[i] ?? null;
    return { index: i, app: t.app, id: t.id, steps: t.steps, played: !!a, ...(a ?? {}), condition: t.condition ?? "base", mastery: !!a?.mastery, reason: a ? a.reason : "not played" };
  });
  const played = rows.filter((r) => r.played);
  const firstMiss = rows.find((r) => !r.mastery) ?? null;
  return {
    programme: levelRun?.programme ?? null,
    level: levelRun?.level ?? null,
    run: levelRun?.id ?? null,
    done: !!levelRun?.done,
    passed: !!levelRun?.done && rows.length > 0 && rows.every((r) => r.mastery),
    score: played.reduce((a, r) => a + (r.score | 0), 0),
    seconds: played.reduce((a, r) => a + (r.seconds | 0), 0),
    parSeconds: played.reduce((a, r) => a + (r.parSeconds | 0), 0),
    steps: rows.reduce((a, r) => a + (r.steps | 0), 0),
    lessons: rows.reduce((a, r) => a + (r.steps | 0), 0),
    hazardHits: played.reduce((a, r) => a + (r.hazardHits | 0), 0),
    mastered: rows.filter((r) => r.mastery).length,
    rows,
    shortfall: firstMiss ? { task: firstMiss.id, reason: firstMiss.reason } : null,
    finishedAt: played.length ? played[played.length - 1].at : null,
  };
}

// ------------------------------------------------------------------ storage

function ladderStorage(storage) {
  if (storage) return storage;
  try { return globalThis.localStorage ?? null; } catch (_) { return null; }
}
export function readLevelRun(storage) {
  try {
    const raw = ladderStorage(storage)?.getItem(LEVEL_RUN_KEY);
    const run = raw ? JSON.parse(raw) : null;
    return run && run.v === 1 && Array.isArray(run.tasks) && Array.isArray(run.attempts) ? run : null;
  } catch (_) { return null; }
}
export function writeLevelRun(run, storage) {
  try { ladderStorage(storage)?.setItem(LEVEL_RUN_KEY, JSON.stringify(run)); return true; } catch (_) { return false; }
}
export function clearLevelRun(storage) {
  try { ladderStorage(storage)?.removeItem(LEVEL_RUN_KEY); } catch (_) { /* ignore */ }
}

// ------------------------------------------------------------------ credentials

function levelBadgeImage(label) {
  const safe = String(label).replace(/[<>&"]/g, "").slice(0, 28);
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="240" height="240"><rect width="240" height="240" rx="24" fill="#0b1219"/>` +
    `<g stroke="#7ee6ff" stroke-width="7" stroke-linecap="round"><line x1="80" y1="30" x2="80" y2="176"/><line x1="160" y1="30" x2="160" y2="176"/>` +
    [52, 82, 112, 142].map((y) => `<line x1="80" y1="${y}" x2="160" y2="${y}"/>`).join("") + `</g>` +
    `<text x="120" y="210" text-anchor="middle" font-family="Arial, sans-serif" font-size="18" fill="#e6f0f6">${safe}</text></svg>`;
  return `data:image/svg+xml;utf8,${encodeURIComponent(svg)}`;
}

/**
 * The Open Badges 2.0 assertion a passed level earns. It carries the level
 * (programme, number, title), its tasks with their step counts, the standards
 * those tasks evidence (as alignment entries), the attempts behind it when a
 * result is given, and the mastery rule in the criteria — so a hall reading
 * it later can tell what was required without this repository to hand.
 *
 * `opts.standards` is a lookup of id → { body, title } (ladders.js exports
 * LADDER_STANDARDS); without it an alignment names the registry id alone.
 */
export function levelBadge(level, {
  programmeName = null, result = null, standards = null,
  issuerName = "SmartCiti.X Training Network", homePage = "https://smartciti.example",
  learnerHome = null, learnerId = null, learnerName = null, actorName = "YOU",
  issuedOn = null,
} = {}) {
  if (!level) return null;
  const pid = level.programme;
  const key = `${pid}-level-${level.n}`;
  const home = learnerHome ?? homePage;
  const who = learnerId ?? actorName;
  const std = (level.standards ?? []).map((id) => ({ id, ...(standards?.[id] ?? {}) }));
  const tasks = (level.tasks ?? []).map((t) => ({ app: t.app, id: t.id, condition: t.condition ?? "base", steps: t.steps }));
  const lessons = level.lessons ?? level.steps;
  const attempts = (result?.rows ?? []).filter((r) => r.attemptId).map((r) => r.attemptId);
  return {
    "@context": "https://w3id.org/openbadges/v2",
    type: "Assertion",
    id: `${home}/credentials/level/${encodeURIComponent(key)}${result?.run ? `/${encodeURIComponent(result.run)}` : ""}`,
    recipient: { type: "url", hashed: false, identity: `${home}/learners/${encodeURIComponent(who)}`, name: learnerName ?? actorName },
    issuedOn: issuedOn ?? result?.finishedAt ?? new Date().toISOString(),
    verification: { type: "hosted" },
    badge: {
      type: "BadgeClass",
      id: `${homePage}/badges/level/${encodeURIComponent(key)}`,
      name: `${programmeName ?? pid} — Level ${level.n}: ${level.title}`,
      description: `Level ${level.n} of ${LADDER_LEVELS} in ${programmeName ?? pid}: ${tasks.length} task${tasks.length === 1 ? "" : "s"} ` +
        `(${tasks.map((t) => `${t.id} under ${conditionLabel(t.condition)}`).join(", ")}) totalling ${lessons} lessons, run back to back` +
        `${level.coaching === false ? " with no coaching" : ""}. ` +
        (std.length ? `Evidenced against ${std.map((s) => s.body ? `${s.body} ${s.title}` : s.id).join("; ")}. ` : "") +
        (level.partial ? `This level is marked partial: ${level.shortfall} lessons short of the ladder's ${LESSON_BAR}-lesson bar. ` : "") +
        "A level evidences readiness against the named standards; it is not a licence or a certification issued by those bodies.",
      image: levelBadgeImage(`Level ${level.n}`),
      criteria: { narrative: `${MASTERY.text} A level passes when one run of it has a mastery run on every one of its tasks, each under its own condition: ${tasks.map((t) => `${t.id} (${t.condition})`).join(", ")}.` },
      issuer: { type: "Profile", id: `${homePage}/issuer`, name: issuerName, url: homePage },
      tags: ["ladder", `level-${level.n}`, pid],
      alignment: std.map((s) => ({
        targetName: s.body ? `${s.body} — ${s.title}` : s.id,
        targetUrl: `${homePage}/standards/${encodeURIComponent(s.id)}`,
        targetCode: s.id,
        ...(s.body ? { targetFramework: s.body } : {}),
      })),
    },
    evidence: attempts.map((id) => ({ id: `${homePage}/xapi/statements/${id}`, name: id })),
    level: {
      programme: pid, n: level.n, title: level.title, coaching: level.coaching !== false,
      steps: level.steps, lessons, partial: !!level.partial, shortfall: level.shortfall | 0,
      tasks, standards: std.map((s) => s.id), hours: level.hours ?? null,
      run: result?.run ?? null, score: result?.score ?? null, attempts,
      masteryRule: { id: MASTERY.id, text: MASTERY.text },
    },
  };
}

/** The xAPI statement a finished level sends: verb passed or failed, the assertion riding along on a pass. */
export function levelXAPI(level, result, {
  homePage = "https://smartciti.example", actorName = "YOU", learnerName = null, learnerId = null, learnerHome = null,
  programmeName = null, assertion = null, app = "smartcity",
} = {}) {
  const ext = (k) => `${homePage}/xapi/ext/${k}`;
  const passed = !!result?.passed;
  return {
    id: `${app}-level-${level.programme}-${level.n}-${result?.run ?? "run"}`,
    timestamp: result?.finishedAt ?? new Date().toISOString(),
    actor: { objectType: "Agent", name: learnerName ?? actorName, account: { homePage: learnerHome ?? homePage, name: learnerId ?? actorName } },
    verb: passed
      ? { id: "http://adlnet.gov/expapi/verbs/passed", display: { "en-US": "passed" } }
      : { id: "http://adlnet.gov/expapi/verbs/failed", display: { "en-US": "failed" } },
    object: {
      objectType: "Activity",
      id: `${homePage}/ladder/${encodeURIComponent(level.programme)}/level/${level.n}`,
      definition: {
        name: { "en-US": `${programmeName ?? level.programme} — Level ${level.n}: ${level.title}` },
        description: { "en-US": `${level.tasks.length} tasks, ${level.lessons ?? level.steps} lessons, run back to back with one shared score.` },
        type: "http://adlnet.gov/expapi/activities/assessment",
      },
    },
    result: {
      success: passed,
      completion: !!result?.done,
      score: { raw: result?.score ?? 0 },
      duration: `PT${result?.seconds ?? 0}S`,
      extensions: {
        [ext("level")]: `${level.programme}:${level.n}`,
        [ext("tasks")]: (result?.rows ?? []).map((r) => ({ id: r.id, condition: r.condition ?? "base", attempt: r.attemptId ?? null, mastery: r.mastery, reason: r.reason ?? null })),
        [ext("standards")]: level.standards ?? [],
        [ext("mastery-rule")]: MASTERY.text,
        [ext("open-badge")]: passed ? assertion : null,
      },
    },
    context: { platform: "SmartCiti.X ~VR Simulators", extensions: { [ext("level-run")]: result?.run ?? null, [ext("partial")]: !!level.partial } },
  };
}
