// Platform channel — how a hosting platform (an LMS, a portal, a metaverse
// world that embeds a station in a frame or a panel) drives an app and hears
// back from it. It sits on top of identity.js and reuses its trust rule:
//
//   * On load, when embedded, the app announces itself upward with
//     { type: "smartcitix:ready", protocol, app } — to any parent, since it
//     carries nothing but the app's name and protocol version.
//   * The host establishes trust the way identity.js already defines it:
//     postMessage({ type: "smartcitix:identity", learner, learner_id,
//     learner_home }) where learner_home equals the host's real origin.
//   * From that origin only, the app accepts commands:
//       smartcitix:open     { sim | room, skipBrief? }   open a station
//       smartcitix:hub      {}                            back to the hub
//       smartcitix:status   {}                            ask for state
//       smartcitix:catalog  {}                            ask for the roster
//   * And it emits, only to that origin (Identity.emit):
//       smartcitix:state     { app, room, stepIndex, stepCount, score, level, ... }
//       smartcitix:catalog   { app, stations: [...] }
//       smartcitix:progress  { sim, step, index, count, score }   each step
//       smartcitix:record    { record }                           each finish (records.js)
//       smartcitix:credential{ assertion }                        each pass (records.js)
//
// The static catalog (WebXR/smartcity/catalog.json, generated by
// tools/gen_catalog.mjs) is the same roster a platform can index without
// loading the app at all: ids, categories, certifications and deep links.

import { Identity } from "./identity.js";

export const PROTOCOL = 1;
export const COMMANDS = ["smartcitix:open", "smartcitix:hub", "smartcitix:status", "smartcitix:catalog"];

export const Platform = {
  app: null,
  _off: null,

  /**
   * Announce readiness (when embedded) and start listening for commands.
   * `onCommand(type, data, reply)` is called only for commands from the
   * learner's home origin; `reply(type, payload)` answers that origin.
   */
  init({ app, onCommand }) {
    this.app = app;
    if (this._off) { this._off(); this._off = null; }
    const handler = (e) => {
      const type = e.data?.type;
      if (!COMMANDS.includes(type)) return;
      const trusted = Identity.current?.homePage;
      if (!trusted || e.origin !== trusted) return;
      const data = { ...e.data }; delete data.type;
      onCommand?.(type, data, (replyType, payload) => this.emit(replyType, payload));
    };
    addEventListener("message", handler);
    this._off = () => removeEventListener("message", handler);
    if (Identity.embedded) {
      try { window.parent.postMessage({ type: "smartcitix:ready", protocol: PROTOCOL, app }, "*"); } catch (_) { /* ignore */ }
    }
    return this;
  },

  /** Post to the learner's home origin only (never broadcast). */
  emit(type, payload) { return Identity.emit(type, { app: this.app, protocol: PROTOCOL, ...payload }); },

  /** Convenience for the per-step heartbeat a live host HUD wants. */
  progress(payload) { return this.emit("smartcitix:progress", payload); },
};
