// Platform channel — how a hosting platform (an LMS, a portal, a metaverse
// world that embeds a station in a frame or a panel) drives an app and hears
// back from it. It sits on top of identity.js and reuses its trust rule:
//
//   * On load, when embedded, the app announces itself upward with
//     { type: "smartcitix:ready", protocol, app } — to any parent, since it
//     carries nothing but the app's name and protocol version.
//   * The host establishes trust the way identity.js already defines it:
//     postMessage({ type: "smartcitix:identity", learner, learner_id,
//     learner_home }) where learner_home equals the host's real origin.
//   * From that origin only, the app accepts commands:
//       smartcitix:open     { sim | room, skipBrief? }   open a station
//       smartcitix:hub      {}                            back to the hub
//       smartcitix:status   {}                            ask for state
//       smartcitix:catalog  {}                            ask for the roster
//   * And it emits, only to that origin (Identity.emit):
//       smartcitix:state     { app, room, stepIndex, stepCount, score, level, ... }
//       smartcitix:catalog   { app, stations: [...] }
//       smartcitix:progress  { sim, step, index, count, score }   each step
//       smartcitix:record    { record }                           each finish (records.js)
//       smartcitix:credential{ assertion }                        each pass (records.js)
//
// The static catalog (WebXR/smartcity/catalog.json, generated by
// tools/gen_catalog.mjs) is the same roster a platform can index without
// loading the app at all: ids, categories, certifications and deep links.
//
// ---------------------------------------------------------------------------
// Protocol 2 — flows
//
// A host that orchestrates more than one station needs more than "open this
// one". Protocol 2 adds the flow channel: the host hands over a flow (a graph
// of nodes with a condition on every edge — see shared/flowhub.js), this app
// runs the nodes that are its to run, and every transition is reported back.
//
//   * Commands, from the learner's home origin only:
//       smartcitix:flow.load    { flow }                 a flow definition (object or JSON text)
//       smartcitix:flow.start   { flowId?, restart? }    begin (or restart) a loaded flow
//       smartcitix:flow.resume  { nodeId, outcome }      the host finished an external node
//   * Events, to that origin only:
//       smartcitix:flow.state    { flow: <state>, transition }   every transition
//       smartcitix:flow.done     { flow: <state> }               the flow reached a terminal node
//       smartcitix:flow.external { flowId, nodeId, node }        a node the HOST runs; we wait
//
// A protocol-1 host never sends a flow command and never sees a flow event, so
// both sides interoperate unchanged; PROTOCOL is the version the app announces
// in `ready` and stamps on every event, and ACCEPTED_HOST_PROTOCOLS is what it
// will take from a host. The trust rule is identity.js's, unchanged: a flow is
// accepted only from the origin the learner's launch context named as home,
// and every flow event goes only there.
//
// The contract above is what a host must speak. The user's host platform is
// Cognition.X, whose orchestration component is called FlowHub; no FlowHub
// specification exists in this repository, so docs/flowhub.md states this as
// the SmartCiti.X side of the contract and nothing here claims to know how
// FlowHub implements or adapts to it.

import { Identity } from "./identity.js";

export const PROTOCOL = 2;
/**
 * What this app will accept from a host: protocol 1 hosts still work. Named for
 * the host side, because observer.js has its own ACCEPTED_PROTOCOLS for the
 * instructor channel and the two are bundled into one file.
 */
export const ACCEPTED_HOST_PROTOCOLS = [1, 2];

export const BASE_COMMANDS = ["smartcitix:open", "smartcitix:hub", "smartcitix:status", "smartcitix:catalog"];

// The flow channel (protocol 2). Named constants rather than literals because
// three apps and the instructor console all have to agree on them, and
// tools/check_flowhub.mjs checks that they do.
export const FLOW_LOAD = "smartcitix:flow.load";
export const FLOW_START = "smartcitix:flow.start";
export const FLOW_RESUME = "smartcitix:flow.resume";
export const FLOW_STATE = "smartcitix:flow.state";
export const FLOW_DONE = "smartcitix:flow.done";
export const FLOW_EXTERNAL = "smartcitix:flow.external";

export const FLOW_COMMANDS = [FLOW_LOAD, FLOW_START, FLOW_RESUME];
export const FLOW_EVENTS = [FLOW_STATE, FLOW_DONE, FLOW_EXTERNAL];

export const COMMANDS = [...BASE_COMMANDS, ...FLOW_COMMANDS];

export const Platform = {
  app: null,
  _off: null,

  /**
   * Announce readiness (when embedded) and start listening for commands.
   * `onCommand(type, data, reply)` is called only for commands from the
   * learner's home origin; `reply(type, payload)` answers that origin.
   */
  init({ app, onCommand }) {
    this.app = app;
    if (this._off) { this._off(); this._off = null; }
    const handler = (e) => {
      const type = e.data?.type;
      if (!COMMANDS.includes(type)) return;
      const trusted = Identity.current?.homePage;
      if (!trusted || e.origin !== trusted) return;
      const data = { ...e.data }; delete data.type;
      onCommand?.(type, data, (replyType, payload) => this.emit(replyType, payload));
    };
    addEventListener("message", handler);
    this._off = () => removeEventListener("message", handler);
    if (Identity.embedded) {
      try { window.parent.postMessage({ type: "smartcitix:ready", protocol: PROTOCOL, app }, "*"); } catch (_) { /* ignore */ }
    }
    return this;
  },

  /** Post to the learner's home origin only (never broadcast). */
  emit(type, payload) { return Identity.emit(type, { app: this.app, protocol: PROTOCOL, ...payload }); },

  /** Convenience for the per-step heartbeat a live host HUD wants. */
  progress(payload) { return this.emit("smartcitix:progress", payload); },

  /**
   * The flow events, named so an app cannot misspell one. `state` is what
   * shared/flowhub.js's stateMessage() produced; it is nested under `flow` so
   * the flow's own protocol version travels beside the channel's rather than
   * overwriting it.
   */
  flowState(state, transition = null) { return this.emit(FLOW_STATE, { flow: state, transition }); },
  flowDone(state) { return this.emit(FLOW_DONE, { flow: state }); },
  /** A node the host runs: we park until smartcitix:flow.resume arrives. */
  flowExternal(payload) { return this.emit(FLOW_EXTERNAL, { ...payload, awaiting: FLOW_RESUME }); },
};
