/**
 * GENERATED FILE — do not hand-edit. Run `node tools/gen_unions.mjs` after
 * changing tools/unions.json or a union entry in tools/standards.json.
 *
 * Every union the platform names, for WebXR/shared/signage.js: the wordmark
 * a sign typesets (abbrev, name, local), the palette (colors, null = the
 * platform's own), the training body from the registry (its id, title and
 * the categories it covers) and the spellings the platform's own text uses
 * (aliases). No logo lives here or anywhere else in the repository; see
 * docs/signage.md.
 */
export const UNIONS = [
  {"id":"afscme","abbrev":"AFSCME","name":"American Federation of State, County and Municipal Employees","aliases":["AFSCME"],"local":null,"colors":null,"trainingBody":"afscme-training","trainingTitle":"AFSCME member education and safety training for public-service and air-district members","scope":["Emergency Services","Environmental Monitoring","Culinary & Hospitality","Water & Environmental","Dental & Oral Health","Community Environmental Justice","Maritime & Ports","Youth Sports & Coaching"],"note":"Public-service, public-health and air-district members."},
  {"id":"atu","abbrev":"ATU","name":"Amalgamated Transit Union","aliases":["ATU"],"local":null,"colors":null,"trainingBody":"atu-training","trainingTitle":"ATU member training for bus and rail transit operations","scope":["Mobility & Transit"],"note":"Bus and rail transit operations."},
  {"id":"bac","abbrev":"BAC","name":"International Union of Bricklayers and Allied Craftworkers","aliases":["BAC"],"local":null,"colors":null,"trainingBody":"bac-imi","trainingTitle":"BAC and the International Masonry Institute — bricklayer, tile and refractory apprenticeship","scope":["Construction & Structural Trades","Building Systems & Facilities","Surface Prep & Coatings"],"note":"Training through the International Masonry Institute."},
  {"id":"bctgm","abbrev":"BCTGM","name":"Bakery, Confectionery, Tobacco Workers and Grain Millers International Union","aliases":["BCTGM"],"local":null,"colors":null,"trainingBody":"bctgm-training","trainingTitle":"BCTGM apprenticeship and safety training for bakery, confectionery and grain milling work","scope":["Manufacturing & Automation","Culinary & Hospitality"],"note":"Bakery and grain-handling work."},
  {"id":"bmwed","abbrev":"BMWED","name":"Brotherhood of Maintenance of Way Employes Division","aliases":["BMWED"],"local":null,"colors":null,"trainingBody":"bmwed-training","trainingTitle":"BMWED roadway worker training for track and structures maintenance","scope":["Mobility & Transit"],"note":"Track and structures maintenance; a division of the Teamsters."},
  {"id":"carpenters","abbrev":"UBC","name":"United Brotherhood of Carpenters and Joiners of America","aliases":["UBC","Carpenters","United Brotherhood of Carpenters","Pile Drivers"],"local":null,"colors":null,"trainingBody":"carpenters-ictf","trainingTitle":"United Brotherhood of Carpenters International Training Fund — carpenter, pile driver and millwright apprenticeship","scope":["Construction & Structural Trades","Water & Environmental","Maritime & Ports","Building Systems & Facilities","Entertainment & Live Events"],"note":"Carpenters, pile drivers and millwrights. The repository names Pile Drivers Local 34 for the marine work only, so no local is carried on the union's general sign."},
  {"id":"cwa","abbrev":"CWA","name":"Communications Workers of America","aliases":["CWA"],"local":null,"colors":null,"trainingBody":"cwa-training","trainingTitle":"CWA member training for outside-plant, tower and broadcast work","scope":["Connectivity & Telecom","Water & Environmental","Maritime & Ports","Entertainment & Live Events","Community Environmental Justice","Environmental Monitoring","Trade Skills Simulator"],"note":"Outside-plant, tower and broadcast work."},
  {"id":"iaff","abbrev":"IAFF","name":"International Association of Fire Fighters","aliases":["IAFF"],"local":null,"colors":null,"trainingBody":"iaff-training","trainingTitle":"IAFF training programmes, including Fire Ground Survival and the peer support model","scope":["Emergency Services"],"note":"Fire and EMS."},
  {"id":"iam","abbrev":"IAM","name":"International Association of Machinists and Aerospace Workers","aliases":["IAM"],"local":null,"colors":null,"trainingBody":"iam-winpisinger-center","trainingTitle":"IAM — the William W. Winpisinger Education and Technology Center's machinist and transportation training","scope":["Mobility & Transit","Manufacturing & Automation","Trade Skills Simulator"],"note":"Machinist and transportation training at the Winpisinger Center."},
  {"id":"iatse","abbrev":"IATSE","name":"International Alliance of Theatrical Stage Employees","aliases":["IATSE"],"local":null,"colors":null,"trainingBody":"iatse-training-trust","trainingTitle":"IATSE Training Trust Fund — stagecraft, rigging and entertainment electrical skills training","scope":["Entertainment & Live Events"],"note":"Stagecraft, rigging and entertainment electrical work."},
  {"id":"ibew","abbrev":"IBEW","name":"International Brotherhood of Electrical Workers","aliases":["IBEW"],"local":null,"colors":null,"trainingBody":"ibew-neca-jatc","trainingTitle":"IBEW/NECA Joint Apprenticeship and Training Committee — inside and outside wireman apprenticeship standards, taught from the electrical training ALLIANCE curriculum","scope":["Energy & Power","Connectivity & Telecom","Building Systems & Facilities","Mobility & Transit","Maritime & Ports","Entertainment & Live Events","Construction & Structural Trades","Manufacturing & Automation","Trade Skills Simulator"],"note":"Inside and outside wireman apprenticeship with NECA. The programmes name IBEW locals in the plural, so no single local is carried."},
  {"id":"ilwu","abbrev":"ILWU","name":"International Longshore and Warehouse Union","aliases":["ILWU"],"local":null,"colors":null,"trainingBody":"ilwu-pma-training","trainingTitle":"ILWU-PMA joint training for longshore, crane and clerk work, and the Inlandboatmen's Union marine division","scope":["Maritime & Ports","Water & Environmental"],"note":"Longshore, crane and clerk work, trained jointly with the PMA."},
  {"id":"ibu","abbrev":"IBU","name":"Inlandboatmen's Union of the Pacific","aliases":["IBU","Inlandboatmen's Union","Inlandboatmen’s Union"],"local":null,"colors":null,"trainingBody":"ilwu-pma-training","trainingTitle":"ILWU-PMA joint training for longshore, crane and clerk work, and the Inlandboatmen's Union marine division","scope":["Maritime & Ports","Water & Environmental"],"note":"The ILWU's marine division: ferry, tug and barge crews."},
  {"id":"ironworkers","abbrev":"IW","name":"International Association of Bridge, Structural, Ornamental and Reinforcing Iron Workers","aliases":["Ironworkers","Iron Workers","IW"],"local":null,"colors":null,"trainingBody":"ironworkers-impact","trainingTitle":"Ironworkers and IMPACT — apprenticeship and safety training for structural, ornamental and reinforcing ironwork","scope":["Construction & Structural Trades","Maritime & Ports","Building Systems & Facilities","Energy & Power"],"note":"Structural, ornamental and reinforcing ironwork, trained with IMPACT."},
  {"id":"iuoe","abbrev":"IUOE","name":"International Union of Operating Engineers","aliases":["IUOE"],"local":null,"colors":null,"trainingBody":"iuoe-training","trainingTitle":"IUOE local training funds and the IUOE National Training Fund — operating and stationary engineer apprenticeship","scope":["Environmental Monitoring","Building Systems & Facilities","Water & Environmental","Construction & Structural Trades","Maritime & Ports","Energy & Power","Community Environmental Justice","Mobility & Transit"],"note":"Operating and stationary engineers. The repository names both Local 3 (operating) and Local 39 (stationary), so no single local is carried."},
  {"id":"iupat","abbrev":"IUPAT","name":"International Union of Painters and Allied Trades","aliases":["IUPAT"],"local":null,"colors":null,"trainingBody":"iupat-fti","trainingTitle":"IUPAT Finishing Trades Institute — industrial painter, glazier and drywall finisher apprenticeship, including lead and containment training","scope":["Surface Prep & Coatings","Construction & Structural Trades","Building Systems & Facilities","Maritime & Ports"],"note":"Industrial painters, glaziers and drywall finishers, trained through the Finishing Trades Institute."},
  {"id":"liuna","abbrev":"LIUNA","name":"Laborers' International Union of North America","aliases":["LIUNA"],"local":"Local 261","colors":null,"trainingBody":"liuna-training-fund","trainingTitle":"LIUNA Training and Education Fund — construction craft laborer, hazardous waste and environmental remediation curricula","scope":["Water & Environmental","Environmental Monitoring","Construction & Structural Trades","Emergency Services","Community Environmental Justice","Maritime & Ports","Energy & Power","Building Systems & Facilities","Surface Prep & Coatings"],"note":"Construction craft laborers and hazardous-waste crews. Local 261 is the one LIUNA local the repository names (the Hunters Point programme)."},
  {"id":"meba","abbrev":"MEBA","name":"Marine Engineers' Beneficial Association","aliases":["MEBA"],"local":null,"colors":null,"trainingBody":"meba-calhoon-school","trainingTitle":"MEBA — the Calhoon MEBA Engineering School's licensed marine engineer training","scope":["Maritime & Ports"],"note":"Licensed marine engineers, trained at the Calhoon MEBA Engineering School."},
  {"id":"naemt","abbrev":"NAEMT","name":"National Association of Emergency Medical Technicians","aliases":["NAEMT"],"local":null,"colors":null,"trainingBody":"naemt-courses","trainingTitle":"NAEMT course programmes — PHTLS, AMLS and EMS Safety","scope":["Emergency Services"],"note":"A professional association rather than a union; listed because the registry files its course programmes under the union body."},
  {"id":"nasw","abbrev":"NASW","name":"National Association of Social Workers","aliases":["NASW"],"local":null,"colors":null,"trainingBody":"nasw-code-of-ethics","trainingTitle":"NASW Code of Ethics and the association's practice standards for social work and crisis counselling","scope":["Emergency Services","Community Environmental Justice","Dental & Oral Health"],"note":"A professional association rather than a union; listed because the registry files its Code of Ethics under the union body."},
  {"id":"seiu","abbrev":"SEIU","name":"Service Employees International Union","aliases":["SEIU"],"local":null,"colors":null,"trainingBody":"seiu-training","trainingTitle":"SEIU and Workers United education and training funds for clinic, garment, food-service and public-service members","scope":["Dental & Oral Health","Sewing & Garment Trades","Culinary & Hospitality","Emergency Services","Community Environmental Justice","Environmental Monitoring","Building Systems & Facilities","Youth Sports & Coaching"],"note":"Clinic, food-service, janitorial and public-service members. The repository names SEIU 87, SEIU-USWW and SEIU 1021, so no single local is carried."},
  {"id":"workers-united","abbrev":"WORKERS UNITED","name":"Workers United","aliases":["Workers United"],"local":null,"colors":null,"trainingBody":"seiu-training","trainingTitle":"SEIU and Workers United education and training funds for clinic, garment, food-service and public-service members","scope":["Dental & Oral Health","Sewing & Garment Trades","Culinary & Hospitality","Emergency Services","Community Environmental Justice","Environmental Monitoring","Building Systems & Facilities","Youth Sports & Coaching"],"note":"Garment and textile workers; an SEIU affiliate, trained through the SEIU and Workers United education funds."},
  {"id":"siu","abbrev":"SIU","name":"Seafarers International Union","aliases":["SIU"],"local":null,"colors":null,"trainingBody":"siu-paul-hall-center","trainingTitle":"SIU — the Paul Hall Center for Maritime Training and Education's unlicensed mariner programmes","scope":["Maritime & Ports"],"note":"Unlicensed mariners, trained at the Paul Hall Center."},
  {"id":"smart","abbrev":"SMART","name":"International Association of Sheet Metal, Air, Rail and Transportation Workers","aliases":["SMART"],"local":null,"colors":null,"trainingBody":"smart-iti","trainingTitle":"SMART and the International Training Institute — sheet metal, rail and transportation apprenticeship","scope":["Mobility & Transit","Building Systems & Facilities","Manufacturing & Automation","Construction & Structural Trades","Trade Skills Simulator"],"note":"Sheet metal and rail transportation, trained through the International Training Institute."},
  {"id":"teamsters","abbrev":"IBT","name":"International Brotherhood of Teamsters","aliases":["Teamsters","IBT"],"local":null,"colors":null,"trainingBody":"teamsters-training","trainingTitle":"Teamsters apprenticeship and driver training programmes, including regulated-soil and yard work","scope":["Environmental Monitoring","Mobility & Transit","Manufacturing & Automation","Culinary & Hospitality","Community Environmental Justice","Maritime & Ports"],"note":"Warehouse, driving and regulated-soil haul."},
  {"id":"twu","abbrev":"TWU","name":"Transport Workers Union of America","aliases":["TWU"],"local":null,"colors":null,"trainingBody":"twu-training","trainingTitle":"TWU member training for transit and airline ground operations","scope":["Mobility & Transit"],"note":"Transit and airline ground operations."},
  {"id":"ua","abbrev":"UA","name":"United Association of Journeymen and Apprentices of the Plumbing and Pipe Fitting Industry of the United States and Canada","aliases":["UA","United Association"],"local":"Local 38","colors":null,"trainingBody":"ua-apprenticeship","trainingTitle":"UA — United Association plumber, pipefitter and HVAC service apprenticeship standards and UA Star certification","scope":["Water & Environmental","Building Systems & Facilities","Trade Skills Simulator","Energy & Power","Manufacturing & Automation","Maritime & Ports","Culinary & Hospitality","Construction & Structural Trades"],"note":"Plumbers, pipefitters and HVAC service. Local 38 is the one UA local the repository names (the Hunters Point programme)."},
  {"id":"uaw","abbrev":"UAW","name":"International Union, United Automobile, Aerospace and Agricultural Implement Workers of America","aliases":["UAW"],"local":null,"colors":null,"trainingBody":"uaw-training","trainingTitle":"UAW joint apprenticeship and skilled-trades training for manufacturing and automation work","scope":["Manufacturing & Automation","Trade Skills Simulator"],"note":"Manufacturing and automation skilled trades."},
  {"id":"ufcw","abbrev":"UFCW","name":"United Food and Commercial Workers International Union","aliases":["UFCW"],"local":null,"colors":null,"trainingBody":"ufcw-training","trainingTitle":"UFCW member training for retail food, clinic and dental support work","scope":["Dental & Oral Health","Manufacturing & Automation","Culinary & Hospitality"],"note":"Retail food, clinic and dental support work."},
  {"id":"unite-here","abbrev":"UNITE HERE","name":"UNITE HERE","aliases":["UNITE HERE"],"local":"Local 2","colors":null,"trainingBody":"unite-here-training","trainingTitle":"UNITE HERE hospitality training funds — cooks, housekeepers, bartenders and banquet staff","scope":["Culinary & Hospitality","Building Systems & Facilities"],"note":"Hotel, food-service and hospitality workers. Local 2 is the one UNITE HERE local the repository names (the culinary, bar and hotel programmes)."},
  {"id":"usw","abbrev":"USW","name":"United Steelworkers","aliases":["USW"],"local":null,"colors":null,"trainingBody":"usw-mazzocchi-center","trainingTitle":"USW Tony Mazzocchi Center health, safety and environmental training","scope":["Environmental Monitoring","Manufacturing & Automation","Energy & Power","Water & Environmental","Community Environmental Justice"],"note":"Plant crews; health, safety and environmental training at the Tony Mazzocchi Center."},
  {"id":"nnu","abbrev":"NNU","name":"National Nurses United","aliases":["NNU"],"local":null,"colors":null,"trainingBody":null,"trainingTitle":null,"scope":[],"note":"Named in the outbreak-response programme; the registry carries no NNU training entry."},
  {"id":"cna","abbrev":"CNA","name":"California Nurses Association","aliases":["CNA"],"local":null,"colors":null,"trainingBody":null,"trainingTitle":null,"scope":[],"note":"Named in the outbreak-response programme; an NNU affiliate. The registry carries no CNA training entry."},
  {"id":"nage","abbrev":"NAGE","name":"National Association of Government Employees","aliases":["NAGE"],"local":null,"colors":null,"trainingBody":null,"trainingTitle":null,"scope":[],"note":"Named in the first-responders programme for EMS locals; an SEIU affiliate. The registry carries no NAGE training entry."},
  {"id":"fop","abbrev":"FOP","name":"Fraternal Order of Police","aliases":["FOP"],"local":null,"colors":null,"trainingBody":null,"trainingTitle":null,"scope":[],"note":"Named in the first-responders programme; the registry carries no FOP training entry."},
  {"id":"ibb","abbrev":"IBB","name":"International Brotherhood of Boilermakers, Iron Ship Builders, Blacksmiths, Forgers and Helpers","aliases":["IBB","Boilermakers"],"local":null,"colors":null,"trainingBody":null,"trainingTitle":null,"scope":[],"note":"Named by the shipyard hot-work station's certification; the registry carries no IBB training entry."},
];
export const UNIONS_BY_ID = Object.fromEntries(UNIONS.map((u) => [u.id, u]));
