/**
 * The Bay World quest layer: data plus pure helpers, owned by BAY3.
 *
 * The data itself lives in ./quests-data.js, generated by
 * `node tools/gen_bay_quests.mjs` from WebXR/smartcity/js/curricula.js —
 * see that script's header and docs/bayworld-quests.md for what is
 * generated versus authored. This file never edits that data; it only
 * combines it and offers pure functions over it.
 *
 * BAY2's quest engine (WebXR/bayworld/, not yet built in every worktree)
 * is expected to own `registerQuests(list)`. Wiring this module in looks
 * like:
 *
 *     import { ALL_QUESTS } from "./js/quests.js";
 *     registerQuests(ALL_QUESTS);
 *
 * This file takes no dependency on that engine, or on BAY1's
 * WebXR/shared/bayworld-data.js — sites and landmarks are referenced by
 * plain name strings (`quest.site`, `egg.landmark`) rather than by import,
 * exactly as the brief for this quest layer asks. tools/check_bay_quests.mjs
 * cross-checks those strings against bayworld-data.js's BAY_SITES and
 * BAY_LANDMARKS only when that file exists in the worktree.
 */
import { MAIN_QUESTS, SIDE_QUESTS, EGG_QUESTS, SIDE_ACTIVITIES, LANDMARK_NOTES } from "./quests-data.js";

export { MAIN_QUESTS, SIDE_QUESTS, EGG_QUESTS, SIDE_ACTIVITIES, LANDMARK_NOTES };

/** Every quest BAY2's registerQuests() should receive, main arc first, then
 *  every programme's side quests, then the egg field notes. Order is
 *  cosmetic — every reference between quests is by `id` and `requires`,
 *  never by array position. */
export const ALL_QUESTS = [...MAIN_QUESTS, ...SIDE_QUESTS, ...EGG_QUESTS];

// --------------------------------------------------------------- lookups

export function getQuestById(id, quests = ALL_QUESTS) {
  return quests.find((q) => q.id === id) ?? null;
}

export function questsByKind(kind, quests = ALL_QUESTS) {
  return quests.filter((q) => q.kind === kind);
}

export function questsForSite(site, quests = ALL_QUESTS) {
  return quests.filter((q) => q.site === site);
}

export function questsForProgramme(programmeId, quests = SIDE_QUESTS) {
  return quests.filter((q) => q.programmeId === programmeId);
}

/** Every distinct station id a quest's "station" steps name, in the order
 *  they first appear. */
export function stationIdsInQuest(quest) {
  const ids = [];
  for (const step of quest.steps) {
    if (step.type === "station" && !ids.includes(step.target)) ids.push(step.target);
  }
  return ids;
}

/** Every distinct station id cited anywhere across a quest list: by a
 *  "station" step, or by an egg's `cites.stationId`. */
export function allCitedStationIds(quests = ALL_QUESTS) {
  const ids = new Set();
  for (const q of quests) {
    for (const id of stationIdsInQuest(q)) ids.add(id);
    if (q.cites?.stationId) ids.add(q.cites.stationId);
  }
  return [...ids];
}

/** Every distinct landmark name an egg quest is sited at. */
export function landmarksCited(quests = ALL_QUESTS) {
  return [...new Set(questsByKind("egg", quests).map((q) => q.landmark).filter(Boolean))];
}

// --------------------------------------------------------------- rewards

/** The same monotone reward curve tools/gen_bay_quests.mjs used to build
 *  every main and side quest's reward.xp: base 100, +150 per tier above
 *  the first. Kept here too (not just in the generator) so an app or a
 *  checker that only imports quests.js — never the generator script —
 *  can still recompute and verify it. */
const XP_BASE = 100;
const XP_STEP = 150;
export function rewardForTier(tier) {
  if (!Number.isInteger(tier) || tier < 1) throw new Error(`rewardForTier: tier must be a positive integer, got ${tier}`);
  return XP_BASE + (tier - 1) * XP_STEP;
}

/** Every (quest, reason) pair where a main/side quest's reward does not
 *  match rewardForTier(quest.tier). Egg quests (tier 0, a flat collectible
 *  reward) are intentionally not tiered and are skipped. Pure — takes a
 *  quest list, returns a plain array, throws nothing. */
export function rewardMonotonicityViolations(quests = ALL_QUESTS) {
  const violations = [];
  for (const q of quests) {
    if (q.kind === "egg") continue;
    const expected = rewardForTier(q.tier);
    if (q.reward?.xp !== expected) {
      violations.push({ id: q.id, tier: q.tier, expectedXp: expected, actualXp: q.reward?.xp });
    }
  }
  return violations;
}

// ------------------------------------------------------------ quest graph

/** True if any quest's `requires` chain (main + side quests only — eggs
 *  never require anything) loops back on itself. Pure DFS, no throwing;
 *  callers that want the actual cycle should use findCycle() instead. */
export function questGraphHasCycle(quests = ALL_QUESTS) {
  return findCycle(quests) !== null;
}

/** Returns the first cycle found, as an array of quest ids from the start
 *  of the cycle back to itself, or null if the `requires` graph is a DAG.
 *  Missing `requires` targets are not a cycle (a dangling reference is a
 *  different kind of bug — tools/check_bay_quests.mjs checks for it
 *  separately) so they are treated as a dead end here. */
export function findCycle(quests = ALL_QUESTS) {
  const byId = new Map(quests.map((q) => [q.id, q]));
  const WHITE = 0, GRAY = 1, BLACK = 2;
  const color = new Map(quests.map((q) => [q.id, WHITE]));
  const stack = [];

  function visit(id) {
    color.set(id, GRAY);
    stack.push(id);
    const q = byId.get(id);
    const next = q?.requires;
    if (next && byId.has(next)) {
      if (color.get(next) === GRAY) {
        const start = stack.indexOf(next);
        return [...stack.slice(start), next];
      }
      if (color.get(next) === WHITE) {
        const found = visit(next);
        if (found) return found;
      }
    }
    stack.pop();
    color.set(id, BLACK);
    return null;
  }

  for (const q of quests) {
    if (color.get(q.id) === WHITE) {
      const found = visit(q.id);
      if (found) return found;
    }
  }
  return null;
}

// ------------------------------------------------------------ site resolution
// Quest data names sites and landmarks by their display names (a programme's
// name for side quests, the hall's own words for the main arc, a public place
// name for eggs); the shared map (shared/bayworld-data.js) keys them by id.
// These resolvers bridge the two so the game and the checker agree.
export const MAIN_SITE_ALIASES = {
  "Trades Heritage Walk": "west-oakland-union-hall",
  "Bay Intermodal Warehouse": "west-oakland-warehouse-district",
  "Class A Training Yard": "west-oakland-truck-yard",
  "Apprenticeship Hall": "west-oakland-union-hall",
  "Financial Coaching Center": "fruitvale-community-college",
  "Wellness Resource Center": "fruitvale-community-college",
};
export const LANDMARK_ALIASES = {
  "Lake Merritt": "lake-necklace", "Lakeside Park": "lake-necklace", "Snow Park": "lake-necklace", "San Antonio Park": "lake-necklace", "Mosswood Park": "lake-necklace",
  "Port of Oakland": "port-cranes", "Middle Harbor Shoreline Park": "tidewater-shoreline-park", "Bay Trail — Oakland Segment": "tidewater-shoreline-park",
  "Jack London Square": "waterfront-square", "Brooklyn Basin": "estuary-marina", "Union Point Park": "estuary-marina", "Estuary Park": "estuary-marina",
  "Alameda Point": "rail-depot", "Alameda Marina": "estuary-marina", "Berkeley Marina": "estuary-marina", "Berkeley Pier": "estuary-marina", "Emeryville Marina": "estuary-marina",
  "Skyline Lookout": "overlook-point", "Redwood Regional Park": "redwood-grove-entrance", "Joaquin Miller Park": "redwood-grove-entrance", "Dimond Canyon Park": "redwood-grove-entrance",
  "Fruitvale Village": "market-street-stalls", "MacArthur BART Station": "elevated-transit-station", "Coliseum Station": "elevated-transit-station",
};
/** The map site a quest happens at: by programme anchor for generated quests, by alias for the main arc, else by exact id or name. */
export function resolveQuestSite(quest, sites) {
  if (!Array.isArray(sites)) return null;
  if (quest.programmeId) { const s = sites.find((x) => (x.programmes || []).includes(quest.programmeId)); if (s) return s; }
  const alias = MAIN_SITE_ALIASES[quest.site];
  return sites.find((x) => x.id === alias || x.id === quest.site || x.name === quest.site) || null;
}
/** The map landmark an egg hides at: by public-name alias, else by exact id or name. */
export function resolveLandmark(name, landmarks) {
  if (!Array.isArray(landmarks)) return null;
  const alias = LANDMARK_ALIASES[name];
  return landmarks.find((x) => x.id === alias || x.id === name || x.name === name) || null;
}
