#!/usr/bin/env python3
"""Inline the Trade Skills Simulator ES modules into one distributable HTML file.

The modular source under WebXR/trades/js is what you edit; this produces
WebXR/trades/dist/trade-skills-simulator.html, a single file that can be dropped
on any static HTTPS host (or opened straight from disk) with no build step and no
module server. Run it after changing anything under WebXR/trades/js.

    python3 tools/bundle_trades.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "WebXR" / "trades"
JS = SRC / "js"
OUT = SRC / "dist" / "trade-skills-simulator.html"

# Concatenation order: definitions before the module that uses them, app last
# because it runs on load.
ORDER = [
    JS / "kit.js",
    JS / "game.js",
    JS / "hub.js",
    JS / "rooms" / "electrical.js",
    JS / "rooms" / "salon.js",
    JS / "rooms" / "kitchen.js",
    JS / "rooms" / "phlebotomy.js",
    JS / "rooms" / "welding.js",
    JS / "app.js",
]

THREE_IMPORT = (
    'import * as THREE from '
    '"https://cdnjs.cloudflare.com/ajax/libs/three.js/0.160.0/three.module.min.js";'
)

IMPORT_RE = re.compile(r"^import\s+[\s\S]*?from\s+[\"'][^\"']+[\"'];\s*$", re.MULTILINE)
EXPORT_BLOCK_RE = re.compile(r"^export\s*\{[^}]*\}\s*;\s*$", re.MULTILINE)
EXPORT_KEYWORD_RE = re.compile(r"^export\s+(?=(const|let|var|function|class|async))", re.MULTILINE)
TOP_DECL_RE = re.compile(r"^(?:const|let|var|function|class)\s+([A-Za-z_$][\w$]*)", re.MULTILINE)
TOP_MULTI_CONST_RE = re.compile(r"^const\s+([^=;\n]+?)\s*=", re.MULTILINE)


def strip_module_syntax(source: str) -> str:
    source = IMPORT_RE.sub("", source)
    source = EXPORT_BLOCK_RE.sub("", source)
    source = EXPORT_KEYWORD_RE.sub("", source)
    return source.strip() + "\n"


def top_level_names(source: str) -> set[str]:
    """Names declared at column zero — the ones that would collide when merged."""
    names = {m.group(1) for m in TOP_DECL_RE.finditer(source)}
    for match in TOP_MULTI_CONST_RE.finditer(source):
        for part in match.group(1).split(","):
            ident = part.strip().split("=")[0].strip()
            if re.fullmatch(r"[A-Za-z_$][\w$]*", ident):
                names.add(ident)
    return names


def main() -> int:
    index = (SRC / "index.html").read_text()
    chunks: list[str] = []
    seen: dict[str, Path] = {}
    clashes: list[str] = []

    for path in ORDER:
        if not path.exists():
            print(f"missing module: {path}", file=sys.stderr)
            return 1
        body = strip_module_syntax(path.read_text())
        for name in sorted(top_level_names(body)):
            if name in seen:
                clashes.append(f"{name}: {seen[name].name} and {path.name}")
            else:
                seen[name] = path
        rel = path.relative_to(SRC)
        chunks.append(f"/* ===== {rel} ===== */\n{body}")

    if clashes:
        print("duplicate top-level names would break the bundle:", file=sys.stderr)
        for clash in clashes:
            print(f"  {clash}", file=sys.stderr)
        return 1

    bundle = THREE_IMPORT + "\n\n" + "\n\n".join(chunks)
    script_tag = '<script type="module" src="./js/app.js"></script>'
    if script_tag not in index:
        print("index.html no longer carries the expected module script tag", file=sys.stderr)
        return 1

    banner = (
        "<!-- Generated by tools/bundle_trades.py from WebXR/trades/js — "
        "edit the modules, not this file. -->\n"
    )
    html = index.replace(script_tag, '<script type="module">\n' + bundle + "\n</script>")
    html = html.replace("<body>", "<body>\n" + banner, 1)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(html)
    print(f"wrote {OUT.relative_to(ROOT)}  ({len(html) / 1024:.0f} KB, {len(ORDER)} modules)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
