#!/usr/bin/env node
/**
 * CITYWORKS (docs/consoles/CITYWORKS.md): roads, sidewalks and solid buildings.
 *
 *   node tools/check_cityworks.mjs            # all ten maps
 *   node tools/check_cityworks.mjs orleans    # one map
 *
 * Every fabric street vertex inside the field and off water, labelled AUTHORED procedural (not the real grid); the road
 * graph per map with its components (the fabric adds none); sidewalks never on water; a collider over every massing
 * building and every site building (with a door toward the road) and the walk stopped at walls; the combined parish +
 * streets build inside NP_BUDGET on the low and high tiers at every site, each street chunk inside CW_BUDGET; the
 * mounts; determinism. Pure Node on the vendored three.js; no browser.
 */
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const WEBXR = join(ROOT, "WebXR");
const imp = (p) => import(pathToFileURL(join(WEBXR, p)));
const t0 = Date.now();
const THREE = await imp("vendor/three/dist/three.module.min.js");
const E = await imp("shared/np-parish.js");
const P = await imp("shared/np-parishes.js");
const W = await imp("shared/np-world.js");
const C = await imp("shared/cw-cityworks.js");
const S = await imp("shared/cw-streets-world.js");

let checks = 0, failed = 0;
function check(ok, msg) { checks++; if (!ok) { failed++; console.log(`  FAIL ${msg}`); } return ok; }
const only = process.argv[2];
const lightsByTier = {};
const maps = P.NP_PARISHES.filter((p) => !only || p.id === only);

for (const p of maps) {
  const tag = p.id, half = (p.size ?? E.NP_SIZE) / 2;
  const fabric = C.CW_FABRIC[p.id];
  const streets = C.cwStreets(p);
  if (P.npRegionOf(p) === "new-orleans") {
    check(!!fabric && /AUTHORED/.test(fabric.provenance) && /not the real street grid/.test(fabric.provenance), `${tag}: the fabric is labelled AUTHORED procedural, not the real street grid`);
    const src = readFileSync(join(WEBXR, "shared", `cw-streets-${p.id}.js`), "utf8");
    check(/GENERATED by tools\/gen_cw_streets\.mjs/.test(src) && /NOT the real street grid/.test(src), `${tag}: cw-streets-${p.id}.js carries the generator and provenance lines`);
    check(streets.length > 0, `${tag}: ${streets.length} fabric streets`);
    let vOut = 0, vWet = 0, edgeWet = 0, n = 0;
    for (const s of streets) {
      check(!!C.CW_CLASSES[s.cls], `${tag}/${s.id}: class ${s.cls} is arterial, collector or local`);
      const c = C.CW_CLASSES[s.cls] ?? C.CW_CLASSES.local;
      const reach = c.width / 2 + (c.sidewalk ? C.CW_KERB + C.CW_SIDEWALK : 0);
      for (let i = 0; i < s.pts.length; i++) {
        const [x, z] = s.pts[i]; n++;
        if (Math.abs(x) > half || Math.abs(z) > half) vOut++;
        if (E.npWaterAt(p, x, z)) vWet++;
        if (c.sidewalk) {
          const b = s.pts[Math.min(i + 1, s.pts.length - 1)], a = s.pts[Math.max(i - 1, 0)], L = Math.hypot(b[0] - a[0], b[1] - a[1]) || 1;
          const nx = -(b[1] - a[1]) / L, nz = (b[0] - a[0]) / L;
          if (E.npWaterAt(p, x + nx * reach, z + nz * reach) || E.npWaterAt(p, x - nx * reach, z - nz * reach)) edgeWet++;
        }
      }
    }
    check(vOut === 0, `${tag}: every street vertex inside the field (${n} vertices, ${vOut} outside)`);
    check(vWet === 0, `${tag}: every street vertex off water (${vWet} wet)`);
    check(edgeWet === 0, `${tag}: every sidewalk edge at a street vertex off water (${edgeWet} wet)`);
    const counts = { arterial: 0, collector: 0, local: 0 }; for (const s of streets) counts[s.cls]++;
    check(JSON.stringify(counts) === JSON.stringify(fabric.counts), `${tag}: counts ${JSON.stringify(counts)} match the module`);
    console.log(`  ${tag}: fabric ${streets.length} streets ${JSON.stringify(counts)}, ${n} vertices, all inside the field and off water`);
  } else {
    check(streets.length === 0, `${tag}: a San Francisco district imports no fabric (kerbs and sidewalks from its own roads)`);
  }

  // Road graph: components per map; the fabric adds none.
  const named = C.cwLines(p).filter((l) => l.named);
  const gNamed = C.cwBuildGraph(named), g = C.cwRoadGraph(p);
  const cNamed = C.cwComponents(gNamed).count, cAll = C.cwComponents(g).count;
  check(g.edges.length >= gNamed.edges.length && g.nodes.length > 0, `${tag}: a road graph (${g.nodes.length} nodes, ${g.edges.length} edges)`);
  check(cAll <= cNamed, `${tag}: road graph ${cAll} component(s) with the fabric, ${cNamed} from the named roads alone (the fabric adds no islands)`);
  check(g.edges.every((e) => e.a !== e.b && (e.width > 0 || e.cls === "ferry") && e.cls && e.a < g.nodes.length && e.b < g.nodes.length), `${tag}: every edge has two nodes, a class and a width`);
  const g2 = C.cwBuildGraph(C.cwLines(p));
  check(JSON.stringify(g2) === JSON.stringify(g), `${tag}: the road graph is deterministic`);
  console.log(`  ${tag}: road graph ${g.nodes.length} nodes / ${g.edges.length} edges, ${cAll} component(s) (named roads alone ${cNamed})`);

  // Sidewalks never on water: sample every sidewalk line's band both sides every 6 m.
  let swOn = 0, swWet = 0;
  for (const l of C.cwLines(p)) {
    if (!l.sidewalk) continue;
    const mid = l.width / 2 + C.CW_KERB + C.CW_SIDEWALK / 2;
    for (const [x, z, yaw] of E.npPointsAlong(l.pts, 6).map((q, i, arr) => { const nx = arr[Math.min(i + 1, arr.length - 1)], pv = arr[Math.max(i - 1, 0)]; return [q[0], q[1], Math.atan2(nx[1] - pv[1], nx[0] - pv[0])]; })) {
      for (const sd of [1, -1]) {
        const sx = x - Math.sin(yaw) * mid * sd, sz = z + Math.cos(yaw) * mid * sd;
        if (!C.cwSidewalkAt(p, sx, sz)) continue;
        swOn++;
        if (E.npWaterAt(p, sx, sz)) swWet++;
      }
    }
  }
  check(swOn > 0, `${tag}: ${swOn} sidewalk samples`);
  check(swWet === 0, `${tag}: sidewalks never on water (${swWet} of ${swOn} samples wet)`);
  check(!C.cwSidewalkAt(p, streets[0]?.pts[0][0] ?? named[0].pts[0][0], streets[0]?.pts[0][1] ?? named[0].pts[0][1]), `${tag}: a street's centreline is not a sidewalk`);

  // Colliders: every massing building (after the filter) and every site building, in every chunk that holds either.
  const keep = C.cwMassFilter(p);
  let buildings = 0, covered = 0, siteBoxes = 0, doorsOk = 0, onStreet = 0;
  const cols = new Map();
  for (let cz = 0; cz < E.NP_CHUNKS_PER_SIDE; cz++) for (let cx = 0; cx < E.NP_CHUNKS_PER_SIDE; cx++) {
    const key = `${cx},${cz}`, boxes = C.cwColliders(p, key);
    cols.set(key, boxes);
    for (const spot of E.npMassingForChunk(p, cx, cz)) {
      if (!C.CW_BUILDINGS[spot.kind]) continue;
      if (!keep(spot)) continue;
      buildings++;
      if (boxes.some((b) => spot.x >= b.min[0] - 10 && spot.x <= b.max[0] + 10 && spot.z >= b.min[2] - 10 && spot.z <= b.max[2] + 10 && b.kind === spot.kind)) covered++;
      const near = C.cwNearestLine(p, spot.x, spot.z, 40, (l) => !l.named);
      if (near && near.d < near.line.width / 2) onStreet++;
    }
    for (const b of boxes) if (b.kind === "site") {
      siteBoxes++;
      const d = b.door, eps = 0.01;
      const onFace = d && ((d.face === "n" && Math.abs(d.z - b.min[2]) < eps) || (d.face === "s" && Math.abs(d.z - b.max[2]) < eps) || (d.face === "w" && Math.abs(d.x - b.min[0]) < eps) || (d.face === "e" && Math.abs(d.x - b.max[0]) < eps));
      if (onFace) doorsOk++;
    }
  }
  check(covered === buildings, `${tag}: colliders cover every massing building (${covered}/${buildings})`);
  check(onStreet === 0, `${tag}: no massing building stands on a fabric street (${onStreet})`);
  check(siteBoxes === p.sites.length, `${tag}: a collider per site building (${siteBoxes}/${p.sites.length})`);
  check(doorsOk === p.sites.length, `${tag}: every site building's door sits on its face toward the road (${doorsOk}/${p.sites.length})`);
  check(JSON.stringify(C.cwColliders(p, "8,8")) === JSON.stringify(cols.get("8,8")), `${tag}: colliders are deterministic`);
  // The walk stops at a wall: walk from 6 m west of each site building toward its centre.
  let stopped = 0;
  for (const b of [...cols.values()].flat().filter((q) => q.kind === "site")) {
    const cx = (b.min[0] + b.max[0]) / 2, cz = (b.min[2] + b.max[2]) / 2;
    let x = b.min[0] - 6, z = cz;
    for (let k = 0; k < 40; k++) [x, z] = C.cwBlockWalk(p, x, z, x + 0.5, z);
    if (x <= b.min[0] && x < cx) stopped++;
  }
  check(stopped === p.sites.length, `${tag}: the walk stops at every site building's wall (${stopped}/${p.sites.length})`);
  console.log(`  ${tag}: ${buildings} massing buildings and ${siteBoxes} site buildings, every one with a collider; ${doorsOk} doors on road faces`);

  // Budgets: the combined build at every site on the low and high tiers.
  for (const tier of ["low", "high"]) {
    const root = new THREE.Group(), start = E.npStartSite(p);
    const world = W.npBuildParish(root, THREE, p, { tier, start: start.position, massFilter: keep });
    const cw = S.cwMountStreets({ THREE, root, parish: p, tier });
    let worstM = 0, worstT = 0, worstChunkT = 0, worstChunkL = 0, worstChunkM = 0;
    for (const s of [start, ...p.sites]) {
      world.update(s.position[0], s.position[1], 999); cw.update(s.position[0], s.position[1], 999);
      const st = world.stats(); worstM = Math.max(worstM, st.meshes); worstT = Math.max(worstT, st.triangles);
      for (const c of cw.chunkStats()) { worstChunkT = Math.max(worstChunkT, c.triangles); worstChunkL = Math.max(worstChunkL, c.lights); worstChunkM = Math.max(worstChunkM, c.meshes); }
    }
    check(worstM <= E.NP_BUDGET.drawCalls, `${tag}/${tier}: parish + streets at most ${E.NP_BUDGET.drawCalls} meshes at every site (worst ${worstM})`);
    check(worstT <= E.NP_BUDGET.triangles, `${tag}/${tier}: parish + streets at most ${E.NP_BUDGET.triangles} triangles at every site (worst ${worstT})`);
    check(worstChunkT <= C.CW_BUDGET.chunkTriangles, `${tag}/${tier}: every street chunk at most ${C.CW_BUDGET.chunkTriangles} triangles (worst ${worstChunkT})`);
    check(worstChunkL <= C.CW_BUDGET.chunkLights && worstChunkM <= C.CW_BUDGET.meshesPerChunk, `${tag}/${tier}: every street chunk one mesh and at most ${C.CW_BUDGET.chunkLights} lights (worst ${worstChunkL})`);
    check(cw.stats().chunks <= (2 * C.CW_STREET_RADIUS[tier] + 1) ** 2, `${tag}/${tier}: streets stream inside ring ${C.CW_STREET_RADIUS[tier]}`);
    const pools = cw.group.getObjectByName("cw-streetlight-pools"), heads = cw.group.getObjectByName("cw-streetlight-heads");
    cw.setNight(true); const lit = pools.visible && heads.material.color.getHex() !== 0x8a8f96;
    cw.setNight(false); check(lit && !pools.visible && heads.material.color.getHex() === 0x8a8f96, `${tag}/${tier}: streetlights light at night and go dark by day`);
    (lightsByTier[tag] ??= {})[tier] = cw.stats().lights;
    if (tier === "high") check(lightsByTier[tag].low <= lightsByTier[tag].high, `${tag}: the phone tier carries no more lights than high (${lightsByTier[tag].low} vs ${lightsByTier[tag].high})`);
    console.log(`  ${tag}/${tier}: worst ${worstM} meshes / ${worstT} triangles with streets; worst street chunk ${worstChunkT} triangles, ${worstChunkL} lights; ${cw.lights.length} streetlights, ${cw.crosswalks.length} crosswalk junctions`);
  }
}

// Mounts and the bundle.
const app = readFileSync(join(WEBXR, "parishes", "js", "app.js"), "utf8");
check(/cwMountStreets\(/.test(app) && /massFilter:\s*cwMassFilter\(parish\)/.test(app) && /cwBlockWalk\(/.test(app) && /setNight\(/.test(app), "the parishes app mounts the streets, the mass filter, the walls and the night lights");
const bundler = readFileSync(join(ROOT, "tools", "bundle_webxr.py"), "utf8");
check(["cw-streets-orleans.js", "cw-cityworks.js", "cw-streets-world.js"].every((f) => bundler.includes(f)), "the bundler carries the cw modules in the parishes page");
const reduced = readFileSync(join(WEBXR, "shared", "cw-streets-world.js"), "utf8");
check(!/requestAnimationFrame|animate\(/.test(reduced.replace(/Nothing animates/g, "")), "nothing in the streets animates (a still world under reduced motion)");

console.log(`check_cityworks: ${checks} checks, ${failed} failed (${((Date.now() - t0) / 1000).toFixed(1)} s)`);
process.exit(failed ? 1 : 0);
