/**
 * Cross-app interoperability (docs/interop.md, tools/briefs/interop-brief.md):
 * one learner, one ledger, one set of records across every app.
 *
 * Headless with stub storage: a pass recorded from a Bay World job board
 * shows in the passport, the ledger pays once for a replayed return, the
 * quest step naming that station advances, the programme chip counts it and
 * the export carries the source app. Then the wiring: every app page's
 * bundle includes passport.js, every job board links home with `&return=`,
 * and no world writes progress to a new localStorage key outside the modules
 * allowed to (the passport and each world's existing store).
 *
 *     node tools/check_interop.mjs           # check
 *     node tools/check_interop.mjs --write   # regenerate shared/passport-programmes.js
 */
import { readFileSync, writeFileSync, existsSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const WEBXR = join(ROOT, "WebXR");
const PROGRAMMES_OUT = join(WEBXR, "shared", "passport-programmes.js");
const errors = [];
const fail = (m) => errors.push(m);
const imp = (rel) => import(pathToFileURL(join(WEBXR, rel)).href);

// ------------------------------------------------ the programme catalogue

const { CURRICULA } = await imp("smartcity/js/curricula.js");
function programmesSource() {
  const lines = CURRICULA.map((c) => `  ${JSON.stringify(c.id)}: { name: ${JSON.stringify(c.name)}, stations: ${JSON.stringify(c.stations.map((s) => s.id))} },`);
  return `// Generated by tools/check_interop.mjs --write from WebXR/smartcity/js/curricula.js —\n`
    + `// edit the curricula, not this file. The programme catalogue the learner passport\n`
    + `// (shared/passport.js) counts against, without every world bundling the full\n`
    + `// curricula text: id -> { name, stations }.\n`
    + `export const PP_PROGRAMMES = {\n${lines.join("\n")}\n};\n`;
}
if (process.argv.includes("--write")) {
  writeFileSync(PROGRAMMES_OUT, programmesSource());
  console.log(`Wrote WebXR/shared/passport-programmes.js (${CURRICULA.length} programmes)`);
  process.exit(0);
}
if (!existsSync(PROGRAMMES_OUT) || readFileSync(PROGRAMMES_OUT, "utf8") !== programmesSource()) {
  fail("WebXR/shared/passport-programmes.js is stale — run node tools/check_interop.mjs --write");
}

// ------------------------------------------------------------ stub storage

function stubStore() {
  const m = new Map();
  return {
    getItem: (k) => (m.has(k) ? m.get(k) : null),
    setItem: (k, v) => { m.set(k, String(v)); },
    removeItem: (k) => { m.delete(k); },
    clear: () => m.clear(),
    keys: () => [...m.keys()],
  };
}
globalThis.localStorage = stubStore();
globalThis.sessionStorage = stubStore();

const pp = await imp("shared/passport.js");
const { TrainingRecords } = await imp("shared/records.js");
const career = await imp("bayworld/js/career.js");
const quests = await imp("bayworld/js/quest-engine.js");
const { BW_SITES } = await imp("bayworld/js/city.js");
const { bwMissionLink } = await imp("bayworld/js/sim.js");

// A learner with Bay World history from before the passport: it must survive.
localStorage.setItem("bayworld-career-v1", JSON.stringify({ reputation: 40, credits: 200, visitedSites: [], seenRecordIds: [], log: [] }));
localStorage.setItem("underwater-career-v1", JSON.stringify({ reputation: 15, credits: 60 }));
const before = pp.ppLedger();
if (before.reputation !== 55 || before.credits !== 260) fail(`ledger does not read the legacy stores: ${before.reputation}/${before.credits}, want 55/260`);

// The board and its link home.
const site = BW_SITES.find((s) => (s.stations ?? []).length && (s.programmes ?? []).length) ?? BW_SITES.find((s) => (s.stations ?? []).length);
const sim = site.stations[0];
const link = bwMissionLink(site, { page: "/WebXR/bayworld/index.html" });
if (!/[?&]from=bayworld/.test(link) || !/[?&]return=/.test(link)) fail(`Bay World's board link carries no from/return: ${link}`);
const u = new URL(link, "https://host.example/WebXR/bayworld/index.html");
const target = pp.ppReturnTarget(u.search, u.href);
if (!target || !target.url.endsWith(`/WebXR/bayworld/index.html#site=${encodeURIComponent(site.id)}`) || target.label !== "Back to Bay World") {
  fail(`the runner cannot read the way home: ${JSON.stringify(target)}`);
}
if (pp.ppReturnTarget("?from=bayworld&return=https%3A%2F%2Fevil.example%2F", "https://host.example/x")) fail("an off-origin return is honoured");
if (pp.ppReturnSite(`#site=${encodeURIComponent(site.id)}`) !== site.id) fail("ppReturnSite does not read #site=");

// A quest waiting on that station.
quests.bwClearQuests();
quests.registerQuests([{ id: "interop-q", title: "Interop", site: site.id, steps: [{ type: "station", target: sim, text: "Run it" }, { type: "goto", target: site.id, text: "Report" }] }]);

// The finished run: the runner writes it through the passport.
const heard = { passed: 0, award: 0, milestone: 0 };
pp.ppOn("station-passed", () => { heard.passed += 1; });
pp.ppOn("award", () => { heard.award += 1; });
pp.ppOn("programme-milestone", () => { heard.milestone += 1; });
const episode = { id: "ep-1" };
const rec = pp.ppRecordStation({ app: "smartcity", source: target.from, simId: sim, simName: sim, stars: 3, hazardHits: 0, errors: 0, score: 900, seconds: 60 }, { episode });
if (TrainingRecords.count() !== 1) fail(`one attempt should write one record, got ${TrainingRecords.count()}`);
if (!rec.passed || rec.source !== "bayworld" || rec.app !== "smartcity") fail(`record lacks pass/source/app: ${JSON.stringify({ p: rec.passed, s: rec.source, a: rec.app })}`);
if (rec.episodeId !== "ep-1" || episode.recordId !== rec.id) fail("record and episode do not carry each other's id");
if (!pp.ppCompleted(sim)) fail("ppCompleted does not show the pass");
if (heard.passed !== 1) fail("station-passed did not fire once");

// The world's return, twice (a replayed Back to Bay World).
function bayWorldReturn() {
  const results = career.bwCollectMissionReturns(TrainingRecords.list(), BW_SITES, { storage: localStorage });
  for (const r of results) {
    pp.ppAward("bayworld", { reputation: r.award.reputationGain, credits: r.award.creditsGain, attemptId: r.entry.id, native: true, reason: r.site.name });
    if (r.entry.passed) pp.ppMarkBoard("bayworld", r.site.id, r.entry.id);
    quests.bwNoteStationReturn(r.site.id, { storage: localStorage });
    quests.bwNoteStationReturn(r.entry.simId, { storage: localStorage });
  }
  return results;
}
const first = bayWorldReturn();
const mid = pp.ppLedger();
const second = bayWorldReturn();
const after = pp.ppLedger();
if (first.length !== 1) fail(`the first return should pay once, paid ${first.length}`);
if (second.length !== 0 || after.reputation !== mid.reputation || after.credits !== mid.credits) fail("a replayed return paid again");
if (mid.reputation <= before.reputation) fail("the return paid nothing into the ledger");
if (pp.ppAward("bayworld", { reputation: 99, attemptId: rec.id }).duplicate !== true) fail("ppAward is not idempotent per attempt id");
if (heard.award !== 1) fail(`award should fire once, fired ${heard.award}`);
if (!pp.ppBoardDone("bayworld", site)) fail("the board is not marked done");
const q = quests.questState(localStorage).find((x) => x.id === "interop-q");
if (!q || q.stepIndex !== 1) fail(`the quest step naming ${sim} did not advance: ${JSON.stringify(q)}`);

// A passport-only source (Fairway's grounds programme) adds on top; the regatta's native share is carved out of Bay World's.
pp.ppAward("fairway", { reputation: 5, credits: 20, attemptId: "fw-1" });
pp.ppAward("regatta", { reputation: 12, credits: 60, attemptId: "rg-1", native: true });
const l3 = pp.ppLedger();
if (l3.reputation !== after.reputation + 5 || l3.bySource.fairway.reputation !== 5 || l3.bySource.regatta.reputation !== 12) fail(`ledger source split wrong: ${JSON.stringify(l3.bySource)}`);
const fresh = pp.ppCompleteReturns("fairway", [{ id: "grounds", name: "Grounds", stations: [sim] }], { pay: () => ({ reputation: 3, credits: 9 }) });
const again = pp.ppCompleteReturns("fairway", [{ id: "grounds", name: "Grounds", stations: [sim] }], { pay: () => ({ reputation: 3, credits: 9 }) });
if (fresh.length !== 1 || again.length !== 0) fail("ppCompleteReturns is not once per attempt");

// The chip counts it.
const progId = pp.ppProgrammeIds().find((id) => pp.ppProgramme(id).total && CURRICULA.find((c) => c.id === id).stations.some((s) => s.id === sim));
if (!progId) fail(`no programme lists ${sim}`);
else {
  const chip = pp.ppProgressChip(null, progId);
  if (!chip || chip.passed !== 1 || chip.stars !== 3) fail(`the programme chip does not count the pass: ${JSON.stringify(chip)}`);
}

// The export carries the source app.
const out = pp.ppExport();
const [head, row] = out.csv.trim().split("\r\n");
const cols = head.split(",");
if (!cols.includes("source") || row.split(",")[cols.indexOf("source")] !== "bayworld") fail("the CSV does not carry the source app");
const st = out.xapi.statements[0];
if (!/Bay World/.test(st.context.platform) || !Object.entries(st.context.extensions).some(([k, v]) => k.endsWith("/source-app") && v === "bayworld")) fail("the xAPI statement does not carry the source app");
const unity = readFileSync(join(ROOT, "exports/unity/SmartCitiX/Runtime/TrainingRecord.cs"), "utf8");
if (!/"source"/.test(unity) || !/public string source;/.test(unity)) fail("TrainingRecord.cs lacks the source field — run node tools/export_unity.mjs");

// Nothing was deleted along the way.
const bw = JSON.parse(localStorage.getItem("bayworld-career-v1"));
if (!(bw.reputation >= 40)) fail("the legacy Bay World career was lost");

// ----------------------------------------------------------------- wiring

const APP_PAGES = {
  smartcity: "smartcity/dist/smartcity-x.html", trades: "trades/dist/trade-skills-simulator.html", holodeck: "holodeck/dist/holodeck.html",
  instructor: "instructor/dist/instructor-console.html", fairway: "fairway/dist/fairway.html", bayworld: "bayworld/dist/bayworld.html",
  underwater: "underwater/dist/underwater.html", regatta: "regatta/dist/regatta.html",
};
for (const [app, rel] of Object.entries(APP_PAGES)) {
  const p = join(WEBXR, rel);
  if (!existsSync(p)) { fail(`${rel} missing — run python3 tools/bundle_webxr.py`); continue; }
  const html = readFileSync(p, "utf8");
  if (!html.includes("/* ===== shared/passport.js ===== */")) fail(`${app}'s bundle does not include passport.js`);
}
const src = (rel) => readFileSync(join(WEBXR, rel), "utf8");
if (!/ppRecordStation\(/.test(src("smartcity/js/app.js")) || /TrainingRecords\.record\(\{/.test(src("smartcity/js/app.js").replace(/seedRecord[^\n]*/g, ""))) fail("SmartCiti.X does not record through the passport");
if (!/ppReturnTarget\(/.test(src("smartcity/js/app.js"))) fail("SmartCiti.X shows no Back to <world> button");
for (const rel of ["trades/js/app.js", "holodeck/js/app.js", "fairway/js/app.js"]) if (!/ppRecordStation\(/.test(src(rel))) fail(`${rel} does not record through the passport`);
for (const rel of ["bayworld/js/app.js", "underwater/js/app.js", "regatta/js/app.js", "fairway/js/app.js"]) {
  if (!/ppProgressChip\(/.test(src(rel))) fail(`${rel}'s job board shows no programme chip`);
  if (!/ppAward\(|ppCompleteReturns\(/.test(src(rel))) fail(`${rel} does not pay into the passport ledger`);
}
for (const rel of ["bayworld/js/sim.js", "underwater/js/dive-sim.js", "regatta/js/events.js"]) if (!/return=/.test(src(rel)) && !/ppLaunchLink/.test(src(rel))) fail(`${rel}'s board link carries no return`);
if (!/ppProgressChip\(/.test(src("instructor/js/app.js"))) fail("the instructor console's learner view shows no programme chip");
const home = readFileSync(join(WEBXR, "index.html"), "utf8");
if (!/data-pp-programme=/.test(home) || !/shared\/passport\.js/.test(home)) fail("the home page's programme rail shows no chip");

// No world writes progress to a new key without going through the passport:
// every storage write in the four worlds names one of the keys that existed
// before it (each world's own career, quest, dive, activity and score store,
// and Fairway's crew tag). A new key fails here until it is routed through
// shared/passport.js or added to this list with a reason in docs/interop.md.
const EXISTING_KEYS = new Set(["BW_CAREER_KEY", "BW_QUEST_KEY", "DV_CAREER_KEY", "DV_DIVES_KEY", "DV_ACTIVITY_KEY", "FAIRWAY_STORAGE_KEY", "CREW_KEY"]);
let writes = 0;
for (const world of ["bayworld", "underwater", "regatta", "fairway"]) {
  for (const f of readdirSync(join(WEBXR, world, "js"))) {
    if (!f.endsWith(".js")) continue;
    const rel = `${world}/js/${f}`;
    for (const m of src(rel).matchAll(/setItem\??\.?\(\s*([^,)]+)/g)) {
      writes += 1;
      if (!EXISTING_KEYS.has(m[1].trim())) fail(`${rel} writes storage key ${m[1].trim()} outside the passport and its world's existing stores`);
    }
  }
}
if (writes < 7) fail(`expected at least 7 existing storage writes in the worlds, found ${writes} — the scan is broken`);
if (!existsSync(join(ROOT, "docs", "interop.md"))) fail("docs/interop.md missing");

if (errors.length) {
  for (const e of errors) console.error(`✗ ${e}`);
  console.error(`\n${errors.length} interop check(s) failed.`);
  process.exit(1);
}
console.log(`All interop checks pass: a Bay World pass recorded once, paid once on a replayed return, quest advanced, chip ${progId} counts it, export carries the source; ${Object.keys(APP_PAGES).length} bundles carry passport.js; ${CURRICULA.length} programmes.`);
