/**
 * The Unity content bridge, held to its brief.
 *
 *     node tools/check_unity_export.mjs
 *
 * exports/unity/SmartCitiX/ is generated by tools/export_unity.mjs and
 * committed, so a Unity project can pull it without running Node. That makes
 * it a copy, and a copy goes stale. This re-runs the content half of the
 * exporter into a scratch folder and diffs it against the committed one, then
 * asks of the committed export:
 *   - every catalog station and every programme has a file, and every JSON parses;
 *   - the C# files have balanced braces and live in the SmartCitiX namespace;
 *   - the UPM manifest and the asmdef are valid;
 *   - the scoring constants the runtime bakes in are game.js's;
 *   - Models/MANIFEST.json names every budget entry with a file that exists or a reason;
 *   - nothing that must not ship is in it: no model name, no token, no avatar, no track GLB.
 */
import { readFileSync, readdirSync, statSync, existsSync, mkdtempSync, rmSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { tmpdir } from "node:os";
import { join, dirname, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { buildSuite } from "./lib/headless.mjs";
import { SCORING } from "./lib/unity_runtime.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "exports", "unity", "SmartCitiX");
let failures = 0;
const fail = (m) => { console.log(`  ✗ ${m}`); failures += 1; };

function walk(dir, out = []) {
  for (const n of readdirSync(dir).sort()) { const p = join(dir, n); if (statSync(p).isDirectory()) walk(p, out); else out.push(p); }
  return out;
}

if (!existsSync(OUT)) { console.log(`  ✗ ${relative(ROOT, OUT)} is missing — run node tools/export_unity.mjs`); process.exit(1); }

// ----------------------------------------------------- 1. up to date
const scratch = mkdtempSync(join(tmpdir(), "unity-check-"));
process.on("exit", () => { try { rmSync(scratch, { recursive: true, force: true }); } catch { /* scratch */ } });
const run = spawnSync(process.execPath, [join(ROOT, "tools", "export_unity.mjs"), "--quiet", "--out", scratch], { encoding: "utf8" });
if (run.status !== 0) fail(`export_unity.mjs failed: ${(run.stderr || run.stdout).trim().split("\n").slice(-3).join(" | ")}`);
else {
  const fresh = walk(scratch).map((p) => relative(scratch, p));
  const committed = walk(OUT).map((p) => relative(OUT, p)).filter((p) => !p.startsWith("Models/"));
  for (const rel of fresh) {
    if (!existsSync(join(OUT, rel))) { fail(`export is stale: ${rel} is not committed`); continue; }
    if (!readFileSync(join(scratch, rel)).equals(readFileSync(join(OUT, rel)))) fail(`export is stale: ${rel} differs from a fresh run — re-run node tools/export_unity.mjs`);
  }
  for (const rel of committed) if (!fresh.includes(rel)) fail(`export has a file the exporter no longer writes: ${rel}`);
}

// --------------------------------------- 2. every station and programme
const catalog = JSON.parse(readFileSync(join(ROOT, "WebXR", "smartcity", "catalog.json"), "utf8"));
const cur = await buildSuite(["smartcity/js/curricula.js"], "export { CURRICULA };", "unity-check-curricula");
let index = null;
const parsed = new Map();
for (const p of walk(join(OUT, "Content")).filter((f) => f.endsWith(".json"))) {
  try { parsed.set(relative(join(OUT, "Content"), p), JSON.parse(readFileSync(p, "utf8"))); } catch (e) { fail(`${relative(ROOT, p)} does not parse: ${e.message}`); }
}
index = parsed.get("index.json");
if (!index) fail("Content/index.json is missing");
const stationFiles = new Set((index?.stations ?? []).map((s) => s.file));
for (const s of catalog.stations) {
  const file = `stations/${s.app === "smartcity" ? "" : s.app + "--"}${s.id}.json`;
  if (!parsed.has(file)) fail(`catalog station ${s.app}/${s.id} has no export (${file})`);
  else {
    const d = parsed.get(file);
    if (d.id !== s.id || d.app !== s.app) fail(`${file}: id/app do not match the catalog`);
    if (!Array.isArray(d.steps)) fail(`${file}: no steps array`);
    for (const st of d.steps ?? []) if (st.unknownKind) fail(`${file}: step ${st.id} has a kind the runtime does not run (${st.kind})`);
    if (!d.flat && !(d.scene?.hits?.length)) fail(`${file}: a built station with no hit ids`);
    if (!stationFiles.has(file)) fail(`index.json does not list ${file}`);
  }
}
for (const c of cur.CURRICULA) {
  const file = `programmes/${c.id}.json`;
  if (!parsed.has(file)) fail(`programme ${c.id} has no export (${file})`);
  else if ((parsed.get(file).stations ?? []).length !== c.stations.length) fail(`${file}: station count differs from curricula.js`);
}
for (const w of ["bayworld", "fairway"]) if (!parsed.has(`worlds/${w}.json`)) fail(`worlds/${w}.json is missing`);
if (existsSync(join(ROOT, "WebXR", "shared", "underwater-data.js")) && !parsed.has("worlds/underwater.json")) fail("underwater-data.js exists but worlds/underwater.json was not exported");
const stationCount = [...parsed.keys()].filter((k) => k.startsWith("stations/")).length;
const programmeCount = [...parsed.keys()].filter((k) => k.startsWith("programmes/")).length;
const worldCount = [...parsed.keys()].filter((k) => k.startsWith("worlds/")).length;

// ------------------------------------------------- 3. the C# runtime
/** Brace balance with strings, chars and comments skipped. */
function braceBalance(src) {
  let depth = 0, i = 0;
  while (i < src.length) {
    const c = src[i], n = src[i + 1];
    if (c === "/" && n === "/") { while (i < src.length && src[i] !== "\n") i++; continue; }
    if (c === "/" && n === "*") { i = src.indexOf("*/", i + 2); if (i < 0) return NaN; i += 2; continue; }
    if (c === '"') {
      const verbatim = src[i - 1] === "@";
      i++;
      while (i < src.length) {
        if (!verbatim && src[i] === "\\") { i += 2; continue; }
        if (src[i] === '"') { if (verbatim && src[i + 1] === '"') { i += 2; continue; } break; }
        i++;
      }
      i++; continue;
    }
    if (c === "'") { i++; while (i < src.length && src[i] !== "'") { if (src[i] === "\\") i++; i++; } i++; continue; }
    if (c === "{") depth++;
    if (c === "}") { depth--; if (depth < 0) return depth; }
    i++;
  }
  return depth;
}
const CS = ["StationCatalog.cs", "StationRunner.cs", "TrainingRecord.cs"];
for (const f of CS) {
  const p = join(OUT, "Runtime", f);
  if (!existsSync(p)) { fail(`Runtime/${f} is missing`); continue; }
  const src = readFileSync(p, "utf8");
  const bal = braceBalance(src);
  if (bal !== 0) fail(`Runtime/${f}: braces do not balance (${Number.isNaN(bal) ? "unterminated comment" : bal})`);
  if (!/^namespace SmartCitiX\s*$/m.test(src)) fail(`Runtime/${f}: not in namespace SmartCitiX`);
  if (!/^using UnityEngine;|^using System;/m.test(src)) fail(`Runtime/${f}: no using directives`);
}
const runnerSrc = existsSync(join(OUT, "Runtime", "StationRunner.cs")) ? readFileSync(join(OUT, "Runtime", "StationRunner.cs"), "utf8") : "";
for (const kind of ["select", "sequence", "find", "gauge", "hold", "track", "turn", "drag", "drive"]) if (!runnerSrc.includes(`"${kind}"`)) fail(`StationRunner.cs does not handle the ${kind} kind`);
if (!runnerSrc.includes("stars >= 2") && !/Stars\s*=\s*Errors == 0/.test(runnerSrc)) fail("StationRunner.cs does not compute stars the way game.js does");
const recordSrc = existsSync(join(OUT, "Runtime", "TrainingRecord.cs")) ? readFileSync(join(OUT, "Runtime", "TrainingRecord.cs"), "utf8") : "";
if (!/stars >= 2 && hazardHits == 0/.test(recordSrc)) fail("TrainingRecord.cs does not state the records.js pass rule (stars >= 2 and no unsafe action)");
const recordsJs = readFileSync(join(ROOT, "WebXR", "shared", "records.js"), "utf8");
const csvCols = recordsJs.match(/const CSV_COLUMNS = \[([\s\S]*?)\];/)?.[1].match(/"([^"]+)"/g)?.map((s) => s.slice(1, -1)) ?? [];
for (const c of csvCols) if (!recordSrc.includes(`"${c}"`)) fail(`TrainingRecord.cs CsvColumns lacks records.js column "${c}"`);

// The scoring constants baked into the runtime are game.js's.
const gameJs = readFileSync(join(ROOT, "WebXR", "shared", "game.js"), "utf8");
for (const [k, v] of Object.entries(SCORING)) {
  const m = gameJs.match(new RegExp(`^export const ${k} = ([0-9.]+);`, "m"));
  if (!m) fail(`game.js no longer exports ${k}`);
  else if (Number(m[1]) !== v) fail(`unity_runtime SCORING.${k} is ${v}; game.js says ${m[1]}`);
}

// ---------------------------------------------- 4. manifest and asmdef
try {
  const pkg = JSON.parse(readFileSync(join(OUT, "package.json"), "utf8"));
  if (pkg.name !== "org.agifuturefoundation.smartcitix") fail(`package.json name is ${pkg.name}`);
  if (!/^\d+\.\d+\.\d+$/.test(pkg.version ?? "")) fail(`package.json version "${pkg.version}" is not semver`);
  if (!pkg.unity || !pkg.displayName || !pkg.description) fail("package.json lacks unity/displayName/description");
} catch (e) { fail(`package.json: ${e.message}`); }
try {
  const asm = JSON.parse(readFileSync(join(OUT, "Runtime", "SmartCitiX.asmdef"), "utf8"));
  if (asm.name !== "SmartCitiX") fail(`asmdef name is ${asm.name}`);
} catch (e) { fail(`Runtime/SmartCitiX.asmdef: ${e.message}`); }
if (!existsSync(join(OUT, "README.md"))) fail("README.md is missing");
else {
  const readme = readFileSync(join(OUT, "README.md"), "utf8");
  for (const word of ["CC0", "CC-BY", "avatar", "track GLB"]) if (!readme.includes(word)) fail(`README.md licence notes do not mention ${word}`);
}

// ------------------------------------------------------ 5. the models
const kits = await buildSuite(["shared/kit.js", "shared/textures.js", "shared/perf.js", "shared/fleet.js", "shared/equipment.js", "shared/toolkit.js"],
  "export { FLEET_BUDGET, EQUIPMENT_BUDGET, TOOLKIT_BUDGET };", "unity-check-kits");
let modelsOk = 0, modelsTotal = 0, modelBytes = 0;
const manifestPath = join(OUT, "Models", "MANIFEST.json");
if (!existsSync(manifestPath)) fail("Models/MANIFEST.json is missing — run node tools/export_unity.mjs --models");
else {
  let manifest;
  try { manifest = JSON.parse(readFileSync(manifestPath, "utf8")); } catch (e) { fail(`Models/MANIFEST.json: ${e.message}`); }
  const byKey = new Map((manifest?.entries ?? []).map((e) => [`${e.kit}/${e.key}`, e]));
  for (const [kit, table] of [["fleet", kits.FLEET_BUDGET], ["equipment", kits.EQUIPMENT_BUDGET], ["toolkit", kits.TOOLKIT_BUDGET]]) {
    for (const key of Object.keys(table ?? {})) {
      modelsTotal += 1;
      const e = byKey.get(`${kit}/${key}`);
      if (!e) { fail(`Models/MANIFEST.json does not name ${kit} ${key}`); continue; }
      if (e.file) {
        const p = join(OUT, "Models", e.file);
        if (!existsSync(p)) fail(`Models/${e.file} (${key}) is named in the manifest but missing`);
        else {
          const buf = readFileSync(p);
          if (buf.length < 12 || buf.toString("latin1", 0, 4) !== "glTF") fail(`Models/${e.file} is not a GLB`);
          modelBytes += buf.length; modelsOk += 1;
        }
      } else if (!e.reason) fail(`Models/MANIFEST.json: ${kit} ${key} has neither a file nor a reason`);
    }
  }
  for (const f of readdirSync(join(OUT, "Models"))) if (/avatar|readyplayer|rpm|track/i.test(f)) fail(`Models/${f} looks like the avatar or the track GLB, which are never exported`);
}

// --------------------------------------------- 6. nothing that must not ship
const FORBIDDEN = [
  [/\b(claude|anthropic|fable|opus|sonnet|haiku|gpt-?\d|openai|gemini)\b/i, "a model or vendor name"],
  [/\bsk-[A-Za-z0-9_-]{16,}/, "an API key"],
  [/\bpk\.eyJ[A-Za-z0-9_-]{10,}/, "a map token"],
  [/\bAKIA[0-9A-Z]{16}\b/, "an AWS key"],
  [/\bgh[pousr]_[A-Za-z0-9]{20,}/, "a GitHub token"],
  [/\bxox[baprs]-[A-Za-z0-9-]{10,}/, "a chat token"],
  [/readyplayer\.me|models\.readyplayer/i, "the avatar service"],
  [/-----BEGIN [A-Z ]*PRIVATE KEY-----/, "a private key"],
];
for (const p of walk(OUT)) {
  const rel = relative(OUT, p);
  const buf = readFileSync(p);
  // A GLB carries its JSON chunk in plain text; scan it as latin1 like any other file.
  const text = buf.toString(rel.endsWith(".glb") ? "latin1" : "utf8");
  for (const [re, what] of FORBIDDEN) if (re.test(text)) fail(`${rel} contains ${what}`);
}

const total = walk(OUT).reduce((n, p) => n + statSync(p).size, 0);
if (total > 40 * 1e6) fail(`the export is ${(total / 1e6).toFixed(1)} MB, over the 40 MB the brief allows`);

console.log(failures
  ? `\n${failures} Unity export problem(s).`
  : `\nUnity export up to date: ${stationCount} stations, ${programmeCount} programmes, ${worldCount} worlds, ${modelsOk}/${modelsTotal} models (${(modelBytes / 1e6).toFixed(1)} MB), ${(total / 1e6).toFixed(1)} MB in all; no token or model name.`);
process.exit(failures ? 1 : 0);
