#!/usr/bin/env node
/**
 * COGNITION — the K-12 learning module gate (docs/consoles/COGNITION.md).
 *
 *   node tools/check_cognition.mjs
 *
 *   1. the generated module is current (tools/gen_cg_units.mjs --check)
 *   2. every K-12 station in the catalog has a flow that validates (flowhub validateFlow against the catalog)
 *   3. every unit resolves to its real programme and real lessons (parish lesson, field lesson or station), in
 *      reading-ceiling order (band ceiling, then grade, never decreasing)
 *   4. Kids rule on generated text: check and re-teach lines hold the lesson's reading ceiling, no digits
 *   5. the adaptive branch: a missed check routes to the re-teach step and returns to the check (main line)
 *   6. the runner finishes every lesson's flow headlessly and reports to SCHOLAR's and DEAN's shapes (stubs)
 *   7. mounted in the parishes app and Redwood Reach
 */
import { readFileSync, existsSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { readingStats } from "./lib/reading-level.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const t0 = Date.now();
let pass = 0; const fails = [];
const ok = () => { pass++; };
const fail = (where, why) => { fails.push(`${where}: ${why}`); };
const line = (s) => console.log(`  ${s}`);

const catalog = JSON.parse(readFileSync(join(ROOT, "WebXR/smartcity/catalog.json"), "utf8"));
const F = await import("../WebXR/shared/flowhub.js");
const CG = await import("../WebXR/shared/cg-runner.js");
const U = await import("../WebXR/shared/cg-units.js");
const BY = await import("../WebXR/shared/by-parish-lessons.js");
const FL = await import("../WebXR/shared/field-lessons.js");
const { RW_FIELD_LESSONS } = await import("../WebXR/redwood/js/rw-lore-data.js");

console.log("check_cognition — the K-12 learning module (unit -> lesson -> flow)");

// 1 — generated output current
const gen = spawnSync(process.execPath, [join(ROOT, "tools/gen_cg_units.mjs"), "--check"], { encoding: "utf8" });
if (gen.status !== 0) fail("gen_cg_units", `output is stale — run node tools/gen_cg_units.mjs (${gen.stdout.trim() || gen.stderr.trim()})`); else ok();
line(`1 generator current: ${gen.status === 0 ? "yes" : "NO"}`);

// 2 — every K-12 station has a flow that validates
const K12_STATIONS = catalog.stations.filter((s) => s.id.startsWith("k12-")).map((s) => s.id);
const units = CG.cgUnits();
const lessonOf = new Map();
for (const u of units) for (const l of u.lessons) if (!lessonOf.has(l.station)) lessonOf.set(l.station, { ...l, unit: u.id });
let withFlow = 0;
for (const id of K12_STATIONS) {
  const l = lessonOf.get(id);
  const flow = l && CG.cgFlow(l.flow);
  if (!flow) { fail(id, "no flow in the learning module"); continue; }
  const v = F.validateFlow(flow, catalog);
  if (!v.ok) { fail(id, `flow ${flow.id} does not validate: ${v.errors.join("; ")}`); continue; }
  if (!flow.nodes.some((n) => n.kind === "station" && n.ref === id)) { fail(id, `flow ${flow.id} has no station node for it`); continue; }
  if (flow.id.startsWith("cg-")) {
    const disk = join(ROOT, "WebXR/flows", `${flow.id}.json`);
    if (!existsSync(disk)) { fail(id, `generated flow ${flow.id} not in WebXR/flows`); continue; }
  }
  withFlow++; ok();
}
const idx = JSON.parse(readFileSync(join(ROOT, "WebXR/flows/index.json"), "utf8"));
const generated = Object.values(U.CG_FLOWS).filter((f) => f.id.startsWith("cg-"));
const inIndex = generated.filter((f) => idx.flows.some((e) => e.id === f.id && e.file === `${f.id}.json`)).length;
if (inIndex !== generated.length) fail("flows/index.json", `${generated.length - inIndex} generated flows missing from the index`); else ok();
line(`2 K-12 stations with a flow that validates: ${withFlow}/${K12_STATIONS.length} (${generated.length} generated by COGNITION, ${inIndex} in flows/index.json)`);

// 3 — units resolve to real lessons, reading-ceiling order
const K12 = catalog.curricula.filter((c) => c.id.startsWith("k12-"));
let lessonsOk = 0, lessonsAll = 0, ordered = 0;
for (const c of K12) {
  const u = units.find((x) => x.programme === c.id);
  if (!u) { fail(c.id, "no unit"); continue; }
  const want = new Set(c.stations.map((s) => s.id));
  const have = new Set(u.lessons.map((l) => l.station));
  for (const id of want) if (!have.has(id)) fail(u.id, `programme station ${id} has no lesson`);
  let prev = -Infinity, prevGrade = -Infinity, inOrder = true;
  for (const l of u.lessons) {
    lessonsAll++;
    const refOk = l.kind === "parish" ? !!BY.byLessonById(l.lessonRef)
      : l.kind === "field" ? !!(FL.K2_FIELD_LESSONS.find((x) => x.id === l.lessonRef) ?? RW_FIELD_LESSONS.find((x) => x.id === l.lessonRef))
      : l.kind === "station" ? l.lessonRef === null : false;
    if (!want.has(l.station)) fail(l.id, `station ${l.station} is not in programme ${c.id}`);
    else if (!refOk) fail(l.id, `lesson ${l.lessonRef} (${l.kind}) does not resolve`);
    else { lessonsOk++; ok(); }
    if (l.ceiling < prev || (l.ceiling === prev && l.grade < prevGrade)) inOrder = false;
    prev = l.ceiling; prevGrade = l.grade;
  }
  if (!inOrder) fail(u.id, "lessons are not in reading-ceiling order"); else { ordered++; ok(); }
}
line(`3 units: ${units.length} (${K12.length} K-12 programmes); lessons resolving to real lessons: ${lessonsOk}/${lessonsAll}; units in reading-ceiling order: ${ordered}/${units.length}`);

// 4 — Kids rule on the generated text
let kidsOk = 0;
for (const f of generated) {
  const l = lessonOf.get(f.meta.cognition.station);
  const chk = f.nodes.find((n) => n.id === "check")?.params?.check;
  const rt = f.nodes.find((n) => n.id === "reteach")?.params?.reteach ?? [];
  const text = [chk?.q, ...(chk?.options ?? []), chk?.why, ...rt].filter(Boolean).join(" ");
  const g = readingStats(text).grade;
  const rtg = readingStats(rt.join(" ")).grade;
  const ceiling = l?.ceiling ?? 11;
  let good = true;
  if (g > ceiling) { fail(f.id, `check and re-teach read at ${g.toFixed(1)}, over the ceiling ${ceiling}`); good = false; }
  if (rt.length < 2) { fail(f.id, "re-teach has fewer than two lines"); good = false; }
  if (rtg > Math.min(ceiling, 7)) { fail(f.id, `re-teach reads at ${rtg.toFixed(1)}, over ${Math.min(ceiling, 7)} (it must be simpler)`); good = false; }
  if (/\d/.test(text)) { fail(f.id, "a digit in generated lesson text (facts rule)"); good = false; }
  if (good) { kidsOk++; ok(); }
}
line(`4 Kids rule on generated check and re-teach text (ceiling held, re-teach at or under grade 7, no digits): ${kidsOk}/${generated.length}`);

// 5 — the adaptive branch returns to the main line
let adaptive = 0;
for (const f of generated) {
  const r = CG.cgFlowRunner(f, { lesson: { title: f.title }, at: () => 0 });
  r.next({}); r.next({}); r.next({ passed: true }); // greet -> brief -> lesson (passed) -> check
  const atCheck = r.phase === "check";
  const chk = f.nodes.find((n) => n.id === "check").params.check;
  const wrong = chk.options.findIndex((_, i) => i !== chk.answer);
  r.next({ answer: wrong });
  const atReteach = r.run.nodeId === "reteach";
  r.next({});
  const back = r.run.nodeId === "check";
  r.next({ answer: chk.answer });
  const onMain = r.run.nodeId === "close";
  if (atCheck && atReteach && back && onMain) { adaptive++; ok(); }
  else fail(f.id, `adaptive branch: check ${atCheck}, re-teach ${atReteach}, back ${back}, main line ${onMain}`);
}
line(`5 adaptive branches (missed check -> re-teach -> check -> main line): ${adaptive}/${generated.length}`);

// 6 — the runner finishes every lesson flow headlessly, reporting to SCHOLAR and DEAN (stubs of their shapes)
let finished = 0, scholar = 0, dean = 0; const lessonsSeen = new Set();
const report = {
  scholar: (lessonId, where) => { if (typeof lessonId === "string" && where && where.world) scholar++; },
  dean: (p) => { if (p && p.module && p.lesson && p.status === "complete") dean++; },
};
for (const u of units) for (const l of u.lessons) {
  if (lessonsSeen.has(l.id)) continue; lessonsSeen.add(l.id);
  const flow = CG.cgFlow(l.flow);
  const r = CG.cgFlowRunner(flow, { lesson: { ...l, unit: u.id }, report, at: () => 0 });
  for (let i = 0; i < 40 && !r.done; i++) {
    const ph = r.phase;
    if (ph === "lesson") r.next({ passed: true });
    else if (ph === "check") r.next({ answer: r.say().options ? flow.nodes.find((n) => n.id === r.run.nodeId).params.check.answer : 0 });
    else if (ph === "apply") r.next({ done: true });
    else r.next({});
  }
  if (r.done && r.state.reported?.status === "complete") { finished++; ok(); }
  else fail(l.id, `runner did not finish flow ${l.flow} (stopped at ${r.run.nodeId}, phase ${r.phase})`);
}
if (scholar !== finished) fail("report", `${scholar} SCHOLAR session reports for ${finished} finished lessons`); else ok();
if (dean !== finished) fail("report", `${dean} DEAN progress reports for ${finished} finished lessons`); else ok();
line(`6 runner finished headlessly: ${finished}/${lessonsSeen.size} lesson flows; reports — SCHOLAR ${scholar}, DEAN ${dean}`);

// 7 — mounted in the parishes app and Redwood Reach
const mounts = [["parishes", "WebXR/parishes/js/app.js"], ["redwood", "WebXR/redwood/js/app.js"]];
let mounted = 0;
for (const [w, p] of mounts) {
  const src = readFileSync(join(ROOT, p), "utf8");
  if (/cg-runner\.js/.test(src) && /cgMountRunner\(/.test(src)) { mounted++; ok(); } else fail(w, `${p} does not mount cgMountRunner`);
}
const rwHere = CG.cgLessonsAt({ world: "redwood" }).length;
const npHere = CG.cgLessonsAt({ world: "parishes" }).length;
line(`7 runner mounted: ${mounted}/${mounts.length} (parishes app, Redwood Reach); lessons placed — parishes ${npHere}, redwood ${rwHere}`);

for (const f of fails.slice(0, 30)) console.log(`  FAIL ${f}`);
console.log(`check_cognition: ${pass} passed, ${fails.length} failed (${Date.now() - t0} ms)`);
process.exit(fails.length ? 1 : 0);
