/**
 * Generates WebXR/shared/ladder-milestones-data.js — the real, honest quote
 * behind a level-ladder milestone toast at levels 5, 10, 15 and 20
 * (docs/ladders.md, "Milestones").
 *
 *     node tools/gen_ladder_milestones.mjs
 *
 * A milestone never invents a fact or a number to celebrate with. Instead,
 * for each of a programme's four milestone levels, this reads the level's
 * own first task — a real station in that programme's own ladder
 * (WebXR/smartcity/js/ladders.js, generated by tools/gen_ladders.mjs) — and
 * lifts that station's own first step's `why` text straight out of its
 * source file (smartcity/js/sims/*.js or trades/js/rooms/*.js), verbatim, up
 * to its own first sentence. That is the one rule a learner is shown: not a
 * paraphrase, not a number this script made up, just the station's own
 * reason for the step, quoted.
 *
 * It is run at the end of tools/gen_catalog.mjs (after tools/gen_ladders.mjs
 * writes ladders.js), so a milestone can never quote a level that no longer
 * exists or a station whose own text has since changed.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const WEBXR = join(ROOT, "WebXR");

/** The four levels a ladder ever celebrates with a milestone. Kept here, not
 *  only in shared/ladder.js, so the generator and the pure rule it feeds
 *  agree by construction (tools/check_ladders.mjs holds the two in step). */
export const MILESTONE_LEVELS = [5, 10, 15, 20];

function sourcePath(app, id) {
  return app === "trades" ? join(WEBXR, "trades", "js", "rooms", `${id}.js`) : join(WEBXR, "smartcity", "js", "sims", `${id}.js`);
}

/** The first step's own `why` text from a station's own source, verbatim,
 *  truncated to its own first sentence (never a fact added, only text after
 *  the first `.`, `!` or `?` dropped) — a very long single-sentence `why`
 *  (some run to a semicolon-free paragraph) is cut at the nearest earlier
 *  word boundary rather than left to run the whole card. */
export function firstStepWhy(src) {
  const at = src.indexOf("steps: [");
  if (at === -1) return null;
  const m = /why:\s*"((?:[^"\\]|\\.)*)"/.exec(src.slice(at));
  if (!m) return null;
  const full = m[1].replace(/\\"/g, '"').replace(/\\n/g, " ").replace(/\\\\/g, "\\").trim();
  const sentence = /^(.*?[.!?])(\s|$)/.exec(full);
  let quote = (sentence ? sentence[1] : full).trim();
  // A generous cap — every first-step `why` in this codebase today is one
  // sentence under 410 characters — so a milestone quote is truncated only
  // if some future station's own why runs well past what every other one
  // does, never as the normal case.
  const CAP = 460;
  if (quote.length > CAP) quote = quote.slice(0, quote.lastIndexOf(" ", CAP)).trim() + "…";
  return quote || null;
}

/** Computes LADDER_MILESTONES and the exact file text, without touching
 *  disk, so tools/check_ladders.mjs can prove the shipped file matches this. */
export async function buildLadderMilestonesData() {
  const { LADDERS } = await import(pathToFileURL(join(WEBXR, "smartcity", "js", "ladders.js")).href);
  const milestones = {};
  for (const ladder of LADDERS) {
    const perLevel = {};
    for (const n of MILESTONE_LEVELS) {
      const level = (ladder.levels ?? []).find((l) => l.n === n);
      const task = level?.tasks?.[0];
      if (!task) continue;
      let src;
      try { src = readFileSync(sourcePath(task.app, task.id), "utf8"); } catch { continue; }
      const quote = firstStepWhy(src);
      if (!quote) continue;
      const stationName = ladder.stations?.[`${task.app}:${task.id}`]?.name ?? task.id;
      perLevel[n] = { quote, stationApp: task.app, stationId: task.id, stationName };
    }
    if (Object.keys(perLevel).length) milestones[ladder.programme] = perLevel;
  }
  const text = `// GENERATED FILE — do not hand-edit. Run \`node tools/gen_ladder_milestones.mjs\`
// (or \`node tools/gen_catalog.mjs\`, which runs it).
//
// The real, honest quote behind a level-ladder milestone toast at levels 5,
// 10, 15 and 20 (docs/ladders.md, "Milestones"). LADDER_MILESTONES maps a
// programme id (WebXR/smartcity/js/ladders.js) to { 5, 10, 15, 20 }, each a
// { quote, stationApp, stationId, stationName }. Every \`quote\` is that
// level's own first task's own first step's own \`why\` text, lifted verbatim
// up to its first sentence from that station's own source file — never
// invented, and never a number that station's own text does not already
// state.
export const MILESTONE_LEVELS = ${JSON.stringify(MILESTONE_LEVELS)};
export const LADDER_MILESTONES = ${JSON.stringify(milestones)};
`;
  return { milestones, text };
}

export async function writeLadderMilestonesData() {
  const { milestones, text } = await buildLadderMilestonesData();
  const outPath = join(WEBXR, "shared", "ladder-milestones-data.js");
  writeFileSync(outPath, text);
  patchLaddersDoc(milestones);
  const total = Object.values(milestones).reduce((a, m) => a + Object.keys(m).length, 0);
  console.log(`Wrote WebXR/shared/ladder-milestones-data.js — ${Object.keys(milestones).length} programmes, ${total} milestone quotes`);
  return outPath;
}

/**
 * docs/ladders.md is generated whole by tools/gen_ladders.mjs, which this
 * script always runs after (tools/gen_catalog.mjs's own order) — so rather
 * than duplicate that generator's own page, this inserts one more section
 * into the page it just wrote, right before "## Content gap", every time.
 * Idempotent: a section already there (from the last run) is replaced, not
 * duplicated.
 */
function patchLaddersDoc(milestones) {
  const mdPath = join(WEBXR, "..", "docs", "ladders.md");
  let md;
  try { md = readFileSync(mdPath, "utf8"); } catch { return; } // no doc yet — gen_ladders.mjs hasn't run
  const startMarker = "\n## Milestones\n";
  const endMarker = "\n## Content gap\n";
  const endAt = md.indexOf(endMarker);
  if (endAt === -1) return; // the page's own shape changed; nothing safe to anchor on
  const startAt = md.indexOf(startMarker);
  const before = startAt === -1 ? md.slice(0, endAt + 1) : md.slice(0, startAt + 1);
  const after = md.slice(endAt);
  const example = milestones["railroad-crafts"]?.[5] ?? Object.values(milestones).find((m) => m[5])?.[5] ?? null;
  const lines = [
    "## Milestones",
    "",
    "Passing level 5, 10, 15 or 20 of any ladder adds one thing to the ordinary results card: a small banner, with a burst of original inline-SVG confetti, quoting one real rule. The quote is never written for the occasion — it is that level's own first task's own first station, its own first step's own reason, lifted verbatim (up to that step's own first sentence) straight out of the station's own source file. A milestone can teach the same rule the level just tested, in the learner's own words for it, or it can teach nothing at all — it never invents a fact or a number to fill the space.",
    "",
    "`tools/gen_ladder_milestones.mjs` builds this once as data, `WebXR/shared/ladder-milestones-data.js`, run at the end of `tools/gen_catalog.mjs` (after this generator writes the ladders themselves, so a milestone can never quote a level or a station that has since changed). `WebXR/shared/ladder.js`'s `levelMilestone(programme, n)` is the pure lookup a level 5/10/15/20 pass resolves against, and `milestoneConfettiSvg(programme, n)` draws the burst — deterministically, so the same programme and level always draw the same one. `WebXR/smartcity/js/app.js`'s `showLevelResults()` shows both; the CSS (`smartcity/index.html`, `.milestone-*`) respects `prefers-reduced-motion`.",
    "",
  ];
  if (example) {
    lines.push(`For example, a level 5 milestone built from ${example.stationName} (\`${example.stationId}\`) quotes: *"${example.quote}"*`, "");
  }
  lines.push(
    "### Checks",
    "",
    "`node tools/check_ladders.mjs` holds this to: every ladder's four milestone levels resolve to a quote that is a verbatim prefix of that exact level's own first task's own station's own first step's own `why` text (and any number inside it traces back to that same text); `shared/ladder-milestones-data.js` matches the generator run now; `milestoneConfettiSvg()` is deterministic per programme and level and differs between them; and `smartcity/js/app.js` and `smartcity/index.html` actually show the toast and its confetti, with a reduced-motion override.",
    "",
  );
  writeFileSync(mdPath, before + lines.join("\n") + after);
}

if (import.meta.url === `file://${process.argv[1]}`) writeLadderMilestonesData();
