/**
 * Generates the practitioner review packet — WebXR/smartcity/REVIEW.md —
 * one section per station and room: the trade, the union and certification
 * it claims, every step with its rationale, every seeded hazard with its
 * consequence text, and a sign-off block. This is what a qualified
 * practitioner in each trade reviews before any record from that station is
 * treated as evidence of readiness; the ledger names that review as the
 * next step and this is the document it happens on.
 *
 *     node tools/gen_review_packet.mjs
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { ROOT, WEBXR, loadSmartCity, loadTrades } from "./lib/headless.mjs";

const city = await loadSmartCity();
const trades = await loadTrades();
const OUT = join(WEBXR, "smartcity", "REVIEW.md");

const kindWord = { select: "Select", sequence: "Sequence", find: "Find", gauge: "Graded reading", hold: "Timed hold", track: "Tracked hold", turn: "Turn", drag: "Carry and place" };
const esc = (s) => String(s ?? "").replace(/\|/g, "\\|");

function section(app, r) {
  const lines = [];
  lines.push(`## ${r.name ?? r.title} (${app === "smartcity" ? "SmartCiti.X" : "Trade Skills"} · \`${r.id}\`)`);
  lines.push("");
  lines.push(`**Category:** ${r.category ?? (app === "trades" ? "Trade Skills Simulator" : "—")}  `);
  lines.push(`**Trade:** ${r.trade ?? "—"}  `);
  if (r.union) lines.push(`**Union:** ${r.union}  `);
  lines.push(`**Certification / standard claimed:** ${r.certification ?? "—"}  `);
  lines.push(`**Tagline:** ${r.tagline ?? "—"}`);
  if (r.flat) lines.push("\n_Flat briefing station: a sourced dossier and knowledge check, no walkable scene._");
  lines.push("");
  lines.push("### Procedure as simulated");
  lines.push("");
  lines.push("| # | Step | Kind | Rationale shown to the learner | Reviewer: correct? |");
  lines.push("|---|---|---|---|---|");
  r.steps.forEach((s, i) => {
    const kind = kindWord[s.kind] ?? s.kind;
    const detail = s.kind === "sequence" || s.kind === "find" ? ` (${s.anyOrder || s.kind === "find" ? "any order" : "strict order"}: ${s.targets.map((t) => s.itemNames?.[t] ?? t).join(", ")})` : "";
    lines.push(`| ${i + 1} | ${esc(s.title)} | ${kind}${esc(detail)} | ${esc(s.why)} | ☐ yes ☐ no — |`);
  });
  lines.push("");
  lines.push("### Seeded hazards (unsafe actions)");
  lines.push("");
  lines.push("| Hazard | Consequence shown to the learner | Reviewer: realistic? |");
  lines.push("|---|---|---|");
  for (const [id, text] of Object.entries(r.hazards ?? {})) lines.push(`| \`${id}\` | ${esc(text)} | ☐ yes ☐ no — |`);
  if (r.dossier?.length) {
    lines.push("");
    lines.push("### Dossier sources");
    lines.push("");
    for (const d of r.dossier) {
      lines.push(`- **${d.title}** — ${d.source?.label ?? ""}${d.source?.url ? ` <${d.source.url}>` : ""}${d.source2 ? `; ${d.source2.label} <${d.source2.url}>` : ""}`);
    }
  }
  lines.push("");
  lines.push("### Reviewer sign-off");
  lines.push("");
  lines.push("| Field | Entry |");
  lines.push("|---|---|");
  lines.push("| Reviewer name and qualification | |");
  lines.push("| Union / employer / training centre | |");
  lines.push("| Date | |");
  lines.push("| Verdict | ☐ Approved as evidence of readiness ☐ Approved with changes below ☐ Not approved |");
  lines.push("| Required changes | |");
  lines.push("");
  return lines.join("\n");
}

const all = [...city.ROOMS.map((r) => ["smartcity", r]), ...trades.ROOMS.map((r) => ["trades", r])];
const byCategory = new Map();
for (const [app, r] of all) { const c = r.category ?? (app === "trades" ? "Trade Skills Simulator" : "Uncategorized"); if (!byCategory.has(c)) byCategory.set(c, []); byCategory.get(c).push([app, r]); }

const head = `# Practitioner review packet — SmartCiti.X ~VR Simulators and Trade Skills Simulator

_Generated by \`node tools/gen_review_packet.mjs\` from the station modules; regenerate after any content change. Do not edit by hand — record verdicts in the sign-off tables and commit, or transcribe them to the tracking system._

**Purpose.** Every station here states a real union trade and a real certification or standard, and scores a learner against an ordered procedure with seeded hazards. Before any training record from a station is treated as evidence of readiness for that certification, a qualified practitioner in the trade reviews the station: is the order of operations right, is every rationale true, is every hazard's consequence realistic, and is the certification claim the right one? This packet is the review document. One section per station, with a sign-off block.

**How to review.** Play the station once (\`smartcity/index.html?sim=<id>\` or \`trades/index.html?room=<id>\`), then work down its tables. Mark each step's rationale and each hazard's consequence yes or no with a note. Sign the block. A station with any "no" is not approved until the change is made and the section regenerated.

**Roster.** ${all.length} stations and rooms across ${byCategory.size} categories.

`;
const toc = [...byCategory.entries()].map(([c, list]) => `- **${c}** — ${list.map(([, r]) => r.name ?? r.title).join(", ")}`).join("\n");
const body = [...byCategory.entries()].map(([c, list]) => `# ${c}\n\n` + list.map(([app, r]) => section(app, r)).join("\n---\n\n")).join("\n\n");
writeFileSync(OUT, head + toc + "\n\n---\n\n" + body + "\n");
console.log(`Wrote ${OUT.replace(ROOT + "/", "")} (${all.length} sections, ${byCategory.size} categories)`);
