/**
 * Generates WebXR/shared/i18n-strings.js from tools/i18n/<lang>.json
 * (console BABEL, tools/briefs/i18n-brief.md, docs/i18n.md).
 *
 *     node tools/gen_i18n.mjs
 *
 * en.json is the source of every key. Each other file carries the same keys;
 * a value of "@en" is the explicit English fallback marker and is left out of
 * the generated table, so trT() falls back to English for it. A value whose
 * {placeholders} differ from English's is a build failure.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
export const I18N_DIR = join(ROOT, "tools", "i18n");
export const I18N_OUT = join(ROOT, "WebXR", "shared", "i18n-strings.js");

/** The 21 languages, in picker order: code, native name, English name. */
export const I18N_LANGS = [
  ["en", "English", "English"], ["es", "Español", "Spanish"], ["fr", "Français", "French"], ["ar", "العربية", "Arabic"],
  ["zh", "简体中文", "Chinese (Simplified)"], ["ru", "Русский", "Russian"], ["pt", "Português", "Portuguese"], ["hi", "हिन्दी", "Hindi"],
  ["bn", "বাংলা", "Bengali"], ["ur", "اردو", "Urdu"], ["id", "Bahasa Indonesia", "Indonesian"], ["sw", "Kiswahili", "Swahili"],
  ["ha", "Hausa", "Hausa"], ["am", "አማርኛ", "Amharic"], ["yo", "Yorùbá", "Yoruba"], ["tr", "Türkçe", "Turkish"],
  ["vi", "Tiếng Việt", "Vietnamese"], ["tl", "Tagalog", "Tagalog"], ["ko", "한국어", "Korean"], ["ja", "日本語", "Japanese"],
  ["de", "Deutsch", "German"],
];
export const I18N_RTL = ["ar", "ur"];
export const I18N_REVIEW = "machine-assisted, needs native-speaker review";
export const I18N_FALLBACK = "@en";

export const i18nPlaceholders = (s) => [...String(s).matchAll(/\{(\w+)\}/g)].map((m) => m[1]).sort().join(",");

/** Read every table; returns { en, tables: {code: obj}, problems: [] }. */
export function i18nLoad() {
  const tables = {};
  for (const [code] of I18N_LANGS) tables[code] = JSON.parse(readFileSync(join(I18N_DIR, `${code}.json`), "utf8"));
  const en = tables.en;
  const keys = Object.keys(en).filter((k) => !k.startsWith("_"));
  const problems = [];
  for (const [code] of I18N_LANGS.slice(1)) {
    const t = tables[code];
    if (t._review !== I18N_REVIEW) problems.push(`${code}.json: _review must be "${I18N_REVIEW}"`);
    for (const k of keys) {
      const v = t[k];
      if (typeof v !== "string" || !v) { problems.push(`${code}.json: missing ${k}`); continue; }
      if (v === I18N_FALLBACK) continue;
      if (i18nPlaceholders(v) !== i18nPlaceholders(en[k])) problems.push(`${code}.json: ${k} placeholders {${i18nPlaceholders(v)}} differ from English {${i18nPlaceholders(en[k])}}`);
    }
    for (const k of Object.keys(t)) if (!k.startsWith("_") && !(k in en)) problems.push(`${code}.json: ${k} is not an English key`);
  }
  return { en, keys, tables, problems };
}

/** The generated module's text. */
export function i18nRender({ keys, tables }) {
  const strings = {};
  for (const [code] of I18N_LANGS) {
    const row = {};
    for (const k of keys) { const v = tables[code][k]; if (typeof v === "string" && v && v !== I18N_FALLBACK) row[k] = v; }
    strings[code] = row;
  }
  const langs = I18N_LANGS.map(([code, name, english]) => ({ code, name, english, dir: I18N_RTL.includes(code) ? "rtl" : "ltr" }));
  return `// Generated by tools/gen_i18n.mjs from tools/i18n/*.json — edit those, not this file.
// Every non-English table is ${I18N_REVIEW} (docs/i18n.md).
export const trLangs = ${JSON.stringify(langs)};
export const trStrings = ${JSON.stringify(strings)};
`;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const data = i18nLoad();
  if (data.problems.length) { for (const p of data.problems) console.log(`✗ ${p}`); process.exit(1); }
  writeFileSync(I18N_OUT, i18nRender(data));
  const own = I18N_LANGS.slice(1).map(([c]) => data.keys.filter((k) => data.tables[c][k] !== I18N_FALLBACK).length);
  console.log(`gen_i18n: wrote WebXR/shared/i18n-strings.js — ${data.keys.length} keys × ${I18N_LANGS.length} languages (${Math.min(...own)}–${Math.max(...own)} translated per language)`);
}
