/**
 * Generates WebXR/shared/ladder-milestones-data.js — the real, honest quote
 * behind a level-ladder milestone toast at levels 5, 10, 15 and 20
 * (docs/ladders.md, "Milestones").
 *
 *     node tools/gen_ladder_milestones.mjs
 *
 * A milestone never invents a fact or a number to celebrate with. Instead,
 * for each of a programme's four milestone levels, this reads the level's
 * own first task — a real station in that programme's own ladder
 * (WebXR/smartcity/js/ladders.js, generated by tools/gen_ladders.mjs) — and
 * lifts that station's own first step's `why` text straight out of its
 * source file (smartcity/js/sims/*.js or trades/js/rooms/*.js), verbatim, up
 * to its own first sentence. That is the one rule a learner is shown: not a
 * paraphrase, not a number this script made up, just the station's own
 * reason for the step, quoted.
 *
 * It is run at the end of tools/gen_catalog.mjs (after tools/gen_ladders.mjs
 * writes ladders.js), so a milestone can never quote a level that no longer
 * exists or a station whose own text has since changed.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const WEBXR = join(ROOT, "WebXR");

/** The four levels a ladder ever celebrates with a milestone. Kept here, not
 *  only in shared/ladder.js, so the generator and the pure rule it feeds
 *  agree by construction (tools/check_ladders.mjs holds the two in step). */
export const MILESTONE_LEVELS = [5, 10, 15, 20];

function sourcePath(app, id) {
  return app === "trades" ? join(WEBXR, "trades", "js", "rooms", `${id}.js`) : join(WEBXR, "smartcity", "js", "sims", `${id}.js`);
}

/** The first step's own `why` text from a station's own source, verbatim,
 *  truncated to its own first sentence (never a fact added, only text after
 *  the first `.`, `!` or `?` dropped) — a very long single-sentence `why`
 *  (some run to a semicolon-free paragraph) is cut at the nearest earlier
 *  word boundary rather than left to run the whole card. */
export function firstStepWhy(src) {
  const at = src.indexOf("steps: [");
  if (at === -1) return null;
  const m = /why:\s*"((?:[^"\\]|\\.)*)"/.exec(src.slice(at));
  if (!m) return null;
  const full = m[1].replace(/\\"/g, '"').replace(/\\n/g, " ").replace(/\\\\/g, "\\").trim();
  const sentence = /^(.*?[.!?])(\s|$)/.exec(full);
  let quote = (sentence ? sentence[1] : full).trim();
  // A generous cap — every first-step `why` in this codebase today is one
  // sentence under 410 characters — so a milestone quote is truncated only
  // if some future station's own why runs well past what every other one
  // does, never as the normal case.
  const CAP = 460;
  if (quote.length > CAP) quote = quote.slice(0, quote.lastIndexOf(" ", CAP)).trim() + "…";
  return quote || null;
}

/** Computes LADDER_MILESTONES and the exact file text, without touching
 *  disk, so tools/check_ladders.mjs can prove the shipped file matches this. */
export async function buildLadderMilestonesData() {
  const { LADDERS } = await import(pathToFileURL(join(WEBXR, "smartcity", "js", "ladders.js")).href);
  const milestones = {};
  for (const ladder of LADDERS) {
    const perLevel = {};
    for (const n of MILESTONE_LEVELS) {
      const level = (ladder.levels ?? []).find((l) => l.n === n);
      const task = level?.tasks?.[0];
      if (!task) continue;
      let src;
      try { src = readFileSync(sourcePath(task.app, task.id), "utf8"); } catch { continue; }
      const quote = firstStepWhy(src);
      if (!quote) continue;
      const stationName = ladder.stations?.[`${task.app}:${task.id}`]?.name ?? task.id;
      perLevel[n] = { quote, stationApp: task.app, stationId: task.id, stationName };
    }
    if (Object.keys(perLevel).length) milestones[ladder.programme] = perLevel;
  }
  const text = `// GENERATED FILE — do not hand-edit. Run \`node tools/gen_ladder_milestones.mjs\`
// (or \`node tools/gen_catalog.mjs\`, which runs it).
//
// The real, honest quote behind a level-ladder milestone toast at levels 5,
// 10, 15 and 20 (docs/ladders.md, "Milestones"). LADDER_MILESTONES maps a
// programme id (WebXR/smartcity/js/ladders.js) to { 5, 10, 15, 20 }, each a
// { quote, stationApp, stationId, stationName }. Every \`quote\` is that
// level's own first task's own first step's own \`why\` text, lifted verbatim
// up to its first sentence from that station's own source file — never
// invented, and never a number that station's own text does not already
// state.
export const MILESTONE_LEVELS = ${JSON.stringify(MILESTONE_LEVELS)};
export const LADDER_MILESTONES = ${JSON.stringify(milestones)};
`;
  return { milestones, text };
}

export async function writeLadderMilestonesData() {
  const { milestones, text } = await buildLadderMilestonesData();
  const outPath = join(WEBXR, "shared", "ladder-milestones-data.js");
  writeFileSync(outPath, text);
  const total = Object.values(milestones).reduce((a, m) => a + Object.keys(m).length, 0);
  console.log(`Wrote WebXR/shared/ladder-milestones-data.js — ${Object.keys(milestones).length} programmes, ${total} milestone quotes`);
  return outPath;
}

if (import.meta.url === `file://${process.argv[1]}`) writeLadderMilestonesData();
