/**
 * AVATARS generator (console AVATARS, docs/avatars.md).
 *
 *     node tools/gen_avatars.mjs
 *
 * 1. Reads the 3D figure's own parts out of shared/kit.js headlessly —
 *    FIGURE_PARTS (the revolved profiles, tone tables and face set) and
 *    OUTFITS — and writes them into the generated block of
 *    shared/av-sprites.js, so every sprite is drawn from the same parts as
 *    the figure and the account chip never has to load three.js to show one.
 * 2. Builds the registry (shared/av-characters.js) and packs one sprite
 *    atlas, WebXR/assets/avatars/av-atlas.svg, with a portrait and a token per
 *    entry, plus av-atlas.json naming every frame, under
 *    AV_ATLAS_BUDGET_BYTES. tools/check_avatars.mjs re-runs both steps in
 *    memory and fails when the tree differs.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import { buildSuite, ROOT, WEBXR } from "./lib/headless.mjs";

const SPRITES = join(WEBXR, "shared/av-sprites.js");
const ATLAS_DIR = join(WEBXR, "assets/avatars");
const COLS = 12, CELL = 64;

/** Step 1: the generated block for av-sprites.js (returns the new source). */
export async function genSpriteParts() {
  const kit = await buildSuite(["shared/kit.js", "shared/textures.js", "shared/perf.js"], "export { FIGURE_PARTS, OUTFITS };", "gen-avatars-kit");
  const parts = JSON.parse(JSON.stringify(kit.FIGURE_PARTS));
  const outfits = JSON.parse(JSON.stringify(kit.OUTFITS));
  const src = readFileSync(SPRITES, "utf8");
  const begin = "// BEGIN GENERATED FIGURE PARTS", end = "// END GENERATED FIGURE PARTS";
  const a = src.indexOf(begin), b = src.indexOf(end);
  if (a < 0 || b < 0) throw new Error("av-sprites.js has lost its generated block markers");
  const head = src.slice(0, src.indexOf("\n", a) + 1);
  const block = `export const AV_PARTS = Object.freeze(${JSON.stringify(parts)});\nexport const AV_OUTFITS = Object.freeze(${JSON.stringify(outfits)});\n`;
  return { source: head + block + src.slice(b), parts, outfits };
}

/** Step 2: the atlas and its frames, from the registry as it is on disk. */
export async function genAtlas(bust = "") {
  const q = bust ? `?${bust}` : "";
  const sprites = await import(pathToFileURL(SPRITES).href + q);
  const reg = await import(pathToFileURL(join(WEBXR, "shared/av-characters.js")).href + q);
  const entries = reg.avCharacters();
  const frames = { version: sprites.AV_SPRITE_VERSION, registry: reg.AV_REGISTRY_VERSION, note: "Generated by tools/gen_avatars.mjs — do not edit. Procedural SVG from shared/av-sprites.js; no image files, no third-party art, no real likeness.", cell: CELL, columns: COLS, atlas: "av-atlas.svg", sprites: {} };
  const cells = [], defs = new Map();
  entries.forEach((e, i) => {
    const look = reg.avLookFor(e);
    const key = sprites.avLookKey(look);
    const rowP = Math.floor(i / COLS) * 2, col = i % COLS;
    const p = { x: col * CELL, y: rowP * CELL, w: CELL, h: CELL }, t = { x: col * CELL, y: (rowP + 1) * CELL, w: CELL, h: CELL };
    frames.sprites[e.sprite] = { id: e.id, kind: e.kind, name: e.name, outfit: e.outfit, key, portrait: p, token: t };
    cells.push(`<svg x="${p.x}" y="${p.y}" width="${CELL}" height="${CELL}" viewBox="0 0 64 64">${inner(sprites.avSpriteSvg(look, { kind: "portrait", id: `${e.id}p`, defs }))}</svg>`);
    cells.push(`<svg x="${t.x}" y="${t.y}" width="${CELL}" height="${CELL}" viewBox="0 0 64 64">${inner(sprites.avSpriteSvg(look, { kind: "token", id: `${e.id}t`, defs }))}</svg>`);
  });
  const rows = Math.ceil(entries.length / COLS) * 2;
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${COLS * CELL}" height="${rows * CELL}" viewBox="0 0 ${COLS * CELL} ${rows * CELL}" role="img" aria-label="SmartCiti.X Holodeck character sprites: ${entries.length} portraits and tokens">\n<!-- Generated by tools/gen_avatars.mjs from shared/av-sprites.js; procedural, no image files, no likeness of anyone real. -->\n<defs>${[...defs.values()].join("")}</defs>\n${cells.join("\n")}\n</svg>\n`;
  const json = JSON.stringify(frames) + "\n";
  return { svg, json, entries, bytes: Buffer.byteLength(svg) + Buffer.byteLength(json), budget: sprites.AV_ATLAS_BUDGET_BYTES };
}

/** The drawing inside a sprite's own <svg> wrapper. */
function inner(markup) {
  return markup.replace(/^<svg[^>]*>/, "").replace(/<\/svg>$/, "");
}

const isMain = process.argv[1] && pathToFileURL(process.argv[1]).href === import.meta.url;
if (isMain) {
  const { source, parts, outfits } = await genSpriteParts();
  writeFileSync(SPRITES, source);
  console.log(`✓ av-sprites.js: ${Object.keys(parts).length} part tables and ${Object.keys(outfits).length} outfits written from kit.js`);
  const atlas = await genAtlas(String(Date.now()));
  mkdirSync(ATLAS_DIR, { recursive: true });
  writeFileSync(join(ATLAS_DIR, "av-atlas.svg"), atlas.svg);
  writeFileSync(join(ATLAS_DIR, "av-atlas.json"), atlas.json);
  console.log(`✓ av-atlas.svg + av-atlas.json: ${atlas.entries.length} entries, ${atlas.entries.length * 2} frames, ${(atlas.bytes / 1024).toFixed(1)} KiB of ${(atlas.budget / 1024).toFixed(0)} KiB`);
  if (atlas.bytes > atlas.budget) { console.log("✗ over the atlas byte budget"); process.exit(1); }
  console.log(`  ${join("WebXR/assets/avatars")} (from ${ROOT})`);
}
