/**
 * Display names for every station a skill gate names (docs/skill-gates.md,
 * QUESTMASTER-2): the lock UI shows "Dock Crane — Container Moves", not
 * "dock-crane-container-moves".
 *
 *     node tools/gen_gate_names.mjs
 *
 * Reads the catalog (WebXR/smartcity/catalog.json) and every gated item's
 * gate — Bay World's generated quests, the side games, Summit's and Redwood's
 * quests, and any other `…GATED…` export a `*-data.js` module under WebXR/
 * makes — and writes WebXR/shared/gate-names-data.js with one entry per
 * referenced station or K-12 station. The module is small (a few dozen
 * names), so every world's bundle can carry it. Never hand-edit the output;
 * tools/check_gates.mjs fails when a gated station has no entry here.
 */
import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const WEBXR = join(ROOT, "WebXR");
export const QM_NAMES_OUT = join(WEBXR, "shared", "gate-names-data.js");

class MemStore {
  constructor() { this.m = new Map(); }
  getItem(k) { return this.m.has(k) ? this.m.get(k) : null; }
  setItem(k, v) { this.m.set(k, String(v)); }
  removeItem(k) { this.m.delete(k); }
  clear() { this.m.clear(); }
}
globalThis.localStorage ??= new MemStore();
globalThis.sessionStorage ??= new MemStore();

function walk(dir, out = []) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) { if (!["dist", "vendor", "node_modules", "assets"].includes(name)) walk(p, out); }
    else if (name.endsWith("-data.js")) out.push(p);
  }
  return out;
}

/** Every gated item the platform declares, from the same sources check_gates reads. */
export async function qmCollectGatedItems() {
  const imp = (p) => import(pathToFileURL(join(WEBXR, p)));
  const items = [];
  const BQ = await imp("bayworld/js/quests.js");
  const SG = await imp("shared/side-games-data.js");
  items.push(...BQ.GATED_QUESTS, ...SG.QM_SIDE_GAMES);
  const seen = new Set(items.map((i) => i.id));
  for (const file of walk(WEBXR)) {
    const src = readFileSync(file, "utf8");
    if (!/export const \w*GATED\w*\s*=/.test(src) || /from\s+["']https?:/.test(src)) continue;
    const mod = await import(pathToFileURL(file));
    for (const [name, v] of Object.entries(mod)) {
      if (!/GATED/.test(name) || !Array.isArray(v)) continue;
      for (const it of v) if (it?.gate && !seen.has(it.id)) { seen.add(it.id); items.push({ ...it, source: relative(WEBXR, file) }); }
    }
  }
  return items;
}

export async function qmBuildGateNames() {
  const catalog = JSON.parse(readFileSync(join(WEBXR, "smartcity", "catalog.json"), "utf8"));
  const byId = new Map((catalog.stations ?? []).map((s) => [s.id, s.name]));
  const ids = new Set();
  for (const it of await qmCollectGatedItems()) for (const id of [...(it.gate.stations ?? []), ...(it.gate.k12 ?? [])]) ids.add(id);
  const names = {};
  const missing = [];
  for (const id of [...ids].sort()) { if (byId.has(id)) names[id] = byId.get(id); else missing.push(id); }
  const body = Object.entries(names).map(([id, n]) => `  ${JSON.stringify(id)}: ${JSON.stringify(n)},`).join("\n");
  const out = `// Generated by tools/gen_gate_names.mjs — do not edit. The catalog's display
// name for every station a skill gate names (docs/skill-gates.md), so the
// lock UI reads "Dock Crane — Container Moves", not the id.
// Names prefixed QM_ (the bundler shares one scope).
export const QM_STATION_NAMES = {
${body}
};
`;
  writeFileSync(QM_NAMES_OUT, out);
  return { count: Object.keys(names).length, missing };
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const r = await qmBuildGateNames();
  console.log(`gate names: ${r.count} stations named -> ${relative(ROOT, QM_NAMES_OUT)}${r.missing.length ? `; not in the catalog: ${r.missing.join(", ")}` : ""}`);
  if (r.missing.length) process.exit(1);
}
